/**
 * GENERATED by scripts/yugcontract-du-redirect-allowlist.ts on audit 2026-08-31.
 * DO NOT EDIT BY HAND — regenerate instead. Read-only audit source:
 * 103 verified _du↔base pairs (name/brand/category/images 100% equal).
 * 97 same-price pairs -> permanent redirect to base.
 * 6 price-diff pairs -> documented here ONLY, never redirected
 * (business decision pending; both prices kept for the decision).
 * The 26 _du orphans are intentionally absent from both lists.
 */
export interface DuRedirectPair {
  duYc: string; duSlug: string; baseYc: string; baseSlug: string;
  duPrice?: string; basePrice?: string;
}

export const DU_ALLOWLIST_AUDIT_DATE = "2026-08-31" as const;

export const DU_REDIRECT_PAIRS: readonly DuRedirectPair[] = [
  {
    duYc: "5924679_du", duSlug: "nabir-dlia-stryzhky-remington-hc-5150-5924679_du",
    baseYc: "5924679", baseSlug: "nabir-dlia-stryzhky-remington-hc-5150-5924679",
  },
  {
    duYc: "5967725_du", duSlug: "kukhonnyi-kombain-philips-hr7778-00-5967725_du",
    baseYc: "5967725", baseSlug: "kukhonnyi-kombain-philips-hr7778-00-5967725",
  },
  {
    duYc: "6284421_du", duSlug: "aksesuar-dlia-brytv-philips-sh50-50-6284421_du",
    baseYc: "6284421", baseSlug: "aksesuar-dlia-brytv-philips-sh50-50-6284421",
  },
  {
    duYc: "6313699_du", duSlug: "kavovarka-krapelna-gorenje-atcm-730-t-6313699_du",
    baseYc: "6313699", baseSlug: "kavovarka-krapelna-gorenje-atcm-730-t-6313699",
  },
  {
    duYc: "6349848_du", duSlug: "vbud-poverkhnia-beko-hiaw-64225-sx-6349848_du",
    baseYc: "6349848", baseSlug: "vbud-poverkhnia-beko-hiaw-64225-sx-6349848",
  },
  {
    duYc: "6376339_du", duSlug: "pylosos-myiuchyi-thomas-aqua-pet-family-6376339_du",
    baseYc: "6376339", baseSlug: "pylosos-myiuchyi-thomas-aqua-pet-family-6376339",
  },
  {
    duYc: "6398700_du", duSlug: "mikrokhvylova-pich-lg-mh6336gib-6398700_du",
    baseYc: "6398700", baseSlug: "mikrokhvylova-pich-lg-mh6336gib-6398700",
  },
  {
    duYc: "6446612_du", duSlug: "blender-statsionarnyi-tefal-bl438831-6446612_du",
    baseYc: "6446612", baseSlug: "blender-statsionarnyi-tefal-bl438831-6446612",
  },
  {
    duYc: "6474753_du", duSlug: "fen-remington-d5715-6474753_du",
    baseYc: "6474753", baseSlug: "fen-remington-d5715-6474753",
  },
  {
    duYc: "6482008_du", duSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008_du",
    baseYc: "6482008", baseSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008",
  },
  {
    duYc: "6489771_du", duSlug: "kukhonnyi-kombain-gorenje-mmc-1000-rl-6489771_du",
    baseYc: "6489771", baseSlug: "kukhonnyi-kombain-gorenje-mmc-1000-rl-6489771",
  },
  {
    duYc: "6496818_du", duSlug: "vbud-poverkhnia-beko-hilw64325sb-6496818_du",
    baseYc: "6496818", baseSlug: "vbud-poverkhnia-beko-hilw64325sb-6496818",
  },
  {
    duYc: "6521818_du", duSlug: "ramka-la-30x40-la-1-110-6521818_du",
    baseYc: "6521818", baseSlug: "ramka-la-30x40-la-1-110-6521818",
  },
  {
    duYc: "6527338_du", duSlug: "nabir-dlia-stryzhky-sencor-shp-320sl-6527338_du",
    baseYc: "6527338", baseSlug: "nabir-dlia-stryzhky-sencor-shp-320sl-6527338",
  },
  {
    duYc: "6615810_du", duSlug: "chainyk-philips-hd9318-00-6615810_du",
    baseYc: "6615810", baseSlug: "chainyk-philips-hd9318-00-6615810",
  },
  {
    duYc: "6629656_du", duSlug: "pylosos-tsyklonnyi-philips-fc9745-09-6629656_du",
    baseYc: "6629656", baseSlug: "pylosos-tsyklonnyi-philips-fc9745-09-6629656",
  },
  {
    duYc: "6651531_du", duSlug: "vypriamliach-dlia-volossia-remington-s7307-aqualisse-extreme-6651531_du",
    baseYc: "6651531", baseSlug: "vypriamliach-dlia-volossia-remington-s7307-aqualisse-extreme-6651531",
  },
  {
    duYc: "6655515_du", duSlug: "multyvarky-tefal-rk905a34-6655515_du",
    baseYc: "6655515", baseSlug: "multyvarky-tefal-rk905a34-6655515",
  },
  {
    duYc: "6661880_du", duSlug: "kavovarka-krapelna-russell-hobbs-27010-56-rh-bilyi-6661880_du",
    baseYc: "6661880", baseSlug: "kavovarka-krapelna-russell-hobbs-27010-56-rh-bilyi-6661880",
  },
  {
    duYc: "6666894_du", duSlug: "aksesuar-dlia-brytv-philips-ss12-50-6666894_du",
    baseYc: "6666894", baseSlug: "aksesuar-dlia-brytv-philips-ss12-50-6666894",
  },
  {
    duYc: "6669622_du", duSlug: "vbud-poverkhnia-gorenje-gktw642syb-bg6bb-g2b-6669622_du",
    baseYc: "6669622", baseSlug: "vbud-poverkhnia-gorenje-gktw642syb-bg6bb-g2b-6669622",
  },
  {
    duYc: "6711226_du", duSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226_du",
    baseYc: "6711226", baseSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226",
  },
  {
    duYc: "6720857_du", duSlug: "skovoroda-bravo-chef-safran-24-sm-b-kryshky-bc-1114-24-6720857_du",
    baseYc: "6720857", baseSlug: "skovoroda-bravo-chef-safran-24-sm-b-kryshky-bc-1114-24-6720857",
  },
  {
    duYc: "6745446_du", duSlug: "mikser-z-chashoiu-tefal-ht464138-6745446_du",
    baseYc: "6745446", baseSlug: "mikser-z-chashoiu-tefal-ht464138-6745446",
  },
  {
    duYc: "6790006_du", duSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006_du",
    baseYc: "6790006", baseSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006",
  },
  {
    duYc: "6811303_du", duSlug: "skovoroda-oscar-best-offer-26-sm-b-kryshky-osr-1108-26-1-6811303_du",
    baseYc: "6811303", baseSlug: "skovoroda-oscar-best-offer-26-sm-b-kryshky-osr-1108-26-1-6811303",
  },
  {
    duYc: "6821456_du", duSlug: "kukh-prylad-tramontina-ability-lopatka-z-prorizamy-neilon-chorna-25155-100-6821456_du",
    baseYc: "6821456", baseSlug: "kukh-prylad-tramontina-ability-lopatka-z-prorizamy-neilon-chorna-25155-100-6821456",
  },
  {
    duYc: "6840744_du", duSlug: "serviz-luminarc-louis-xv-white-18-pr-v2940-6840744_du",
    baseYc: "6840744", baseSlug: "serviz-luminarc-louis-xv-white-18-pr-v2940-6840744",
  },
  {
    duYc: "6871226_du", duSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syw-mxy55z-6871226_du",
    baseYc: "6871226", baseSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syw-mxy55z-6871226",
  },
  {
    duYc: "6875715_du", duSlug: "vbud-dukhovka-gorenje-bps-6747-a06bg-6875715_du",
    baseYc: "6875715", baseSlug: "vbud-dukhovka-gorenje-bps-6747-a06bg-6875715",
  },
  {
    duYc: "6884549_du", duSlug: "fen-remington-ac5860-e51-botanicals-hairdryer-6884549_du",
    baseYc: "6884549", baseSlug: "fen-remington-ac5860-e51-botanicals-hairdryer-6884549",
  },
  {
    duYc: "6885495_du", duSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495_du",
    baseYc: "6885495", baseSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495",
  },
  {
    duYc: "6906759_du", duSlug: "viknomyika-idea-home-ds-1534-20-blue-d-vikon-teleskop-112x20-sm-ds-1534-20-blue-6906759_du",
    baseYc: "6906759", baseSlug: "viknomyika-idea-home-ds-1534-20-blue-d-vikon-teleskop-112x20-sm-ds-1534-20-blue-6906759",
  },
  {
    duYc: "6924604_du", duSlug: "kholodylnyk-hisense-rb440n4afe-bcd-331w-6924604_du",
    baseYc: "6924604", baseSlug: "kholodylnyk-hisense-rb440n4afe-bcd-331w-6924604",
  },
  {
    duYc: "6932802_du", duSlug: "kondytsioner-ergo-aci-0923-swn-w-6932802_du",
    baseYc: "6932802", baseSlug: "kondytsioner-ergo-aci-0923-swn-w-6932802",
  },
  {
    duYc: "6932803_du", duSlug: "kondytsioner-ergo-aci-1223-swn-w-6932803_du",
    baseYc: "6932803", baseSlug: "kondytsioner-ergo-aci-1223-swn-w-6932803",
  },
  {
    duYc: "6965981_du", duSlug: "blender-statsionarnyi-tefal-perfect-mix-bl87g831-6965981_du",
    baseYc: "6965981", baseSlug: "blender-statsionarnyi-tefal-perfect-mix-bl87g831-6965981",
  },
  {
    duYc: "6976884_du", duSlug: "toster-moulinex-lt2m0810-6976884_du",
    baseYc: "6976884", baseSlug: "toster-moulinex-lt2m0810-6976884",
  },
  {
    duYc: "6984892_du", duSlug: "morozylna-kamera-hisense-fv298n4ace-6984892_du",
    baseYc: "6984892", baseSlug: "morozylna-kamera-hisense-fv298n4ace-6984892",
  },
  {
    duYc: "6988689_du", duSlug: "chainyk-amica-kf-1002-6988689_du",
    baseYc: "6988689", baseSlug: "chainyk-amica-kf-1002-6988689",
  },
  {
    duYc: "6990162_du", duSlug: "kholodylnyk-hisense-rq760n4ife-6990162_du",
    baseYc: "6990162", baseSlug: "kholodylnyk-hisense-rq760n4ife-6990162",
  },
  {
    duYc: "6992422_du", duSlug: "ramka-evg-inno-zb-4-3636-1-white-collage-4-6992422_du",
    baseYc: "6992422", baseSlug: "ramka-evg-inno-zb-4-3636-1-white-collage-4-6992422",
  },
  {
    duYc: "6993614_du", duSlug: "morozhenytsia-gorenje-icm10w-ice-1031-6993614_du",
    baseYc: "6993614", baseSlug: "morozhenytsia-gorenje-icm10w-ice-1031-6993614",
  },
  {
    duYc: "6993837_du", duSlug: "mikrokhvylova-pich-hisense-h30mobs10hc-6993837_du",
    baseYc: "6993837", baseSlug: "mikrokhvylova-pich-hisense-h30mobs10hc-6993837",
  },
  {
    duYc: "6996159_du", duSlug: "pralna-mashyna-haier-hw90-b14939s8-6996159_du",
    baseYc: "6996159", baseSlug: "pralna-mashyna-haier-hw90-b14939s8-6996159",
  },
  {
    duYc: "7007001_du", duSlug: "sushylna-mashyna-hisense-dh7s107bw-7007001_du",
    baseYc: "7007001", baseSlug: "sushylna-mashyna-hisense-dh7s107bw-7007001",
  },
  {
    duYc: "7019427_du", duSlug: "praska-gorenje-sih3200wr-hl-8002-7019427_du",
    baseYc: "7019427", baseSlug: "praska-gorenje-sih3200wr-hl-8002-7019427",
  },
  {
    duYc: "7022284_du", duSlug: "trymer-philips-oneblade-pro-360-qp6542-15-dlia-oblychchia-ta-tila-7022284_du",
    baseYc: "7022284", baseSlug: "trymer-philips-oneblade-pro-360-qp6542-15-dlia-oblychchia-ta-tila-7022284",
  },
  {
    duYc: "7023706_du", duSlug: "elektropich-hisense-hom45d-7023706_du",
    baseYc: "7023706", baseSlug: "elektropich-hisense-hom45d-7023706",
  },
  {
    duYc: "7024506_du", duSlug: "kukhonna-mashyna-gorenje-mmc1000scb-7024506_du",
    baseYc: "7024506", baseSlug: "kukhonna-mashyna-gorenje-mmc1000scb-7024506",
  },
  {
    duYc: "7024832_du", duSlug: "hryl-philips-hd6307-70-7024832_du",
    baseYc: "7024832", baseSlug: "hryl-philips-hd6307-70-7024832",
  },
  {
    duYc: "7025027_du", duSlug: "fen-philips-bhd538-30-7025027_du",
    baseYc: "7025027", baseSlug: "fen-philips-bhd538-30-7025027",
  },
  {
    duYc: "7051690_du", duSlug: "skorovarka-hisense-hmc6sbk-7051690_du",
    baseYc: "7051690", baseSlug: "skorovarka-hisense-hmc6sbk-7051690",
  },
  {
    duYc: "7053687_du", duSlug: "fen-shchitka-rowenta-cf9840f0-7053687_du",
    baseYc: "7053687", baseSlug: "fen-shchitka-rowenta-cf9840f0-7053687",
  },
  {
    duYc: "7056171_du", duSlug: "mikrokhvylova-pich-hisense-h25mobs4hgi-7056171_du",
    baseYc: "7056171", baseSlug: "mikrokhvylova-pich-hisense-h25mobs4hgi-7056171",
  },
  {
    duYc: "7064284_du", duSlug: "multypich-philips-na332-00-7064284_du",
    baseYc: "7064284", baseSlug: "multypich-philips-na332-00-7064284",
  },
  {
    duYc: "7067155_du", duSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155_du",
    baseYc: "7067155", baseSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155",
  },
  {
    duYc: "7086538_du", duSlug: "kholodylnyk-hisense-rq5p470sale-7086538_du",
    baseYc: "7086538", baseSlug: "kholodylnyk-hisense-rq5p470sale-7086538",
  },
  {
    duYc: "7088394_du", duSlug: "buterbrodnytsia-gorenje-wm1400sb-7088394_du",
    baseYc: "7088394", baseSlug: "buterbrodnytsia-gorenje-wm1400sb-7088394",
  },
  {
    duYc: "7109372_du", duSlug: "hryl-gorenje-gcg2000sd-7109372_du",
    baseYc: "7109372", baseSlug: "hryl-gorenje-gcg2000sd-7109372",
  },
  {
    duYc: "7120201_du", duSlug: "ramka-evg-inno-zb-6fa-3348-white-collage-6-7120201_du",
    baseYc: "7120201", baseSlug: "ramka-evg-inno-zb-6fa-3348-white-collage-6-7120201",
  },
  {
    duYc: "7138500_du", duSlug: "pylosos-myiuchyi-thomas-amfibia-pro-evo-7138500_du",
    baseYc: "7138500", baseSlug: "pylosos-myiuchyi-thomas-amfibia-pro-evo-7138500",
  },
  {
    duYc: "7153553_du", duSlug: "parova-shchitka-philips-sth7030-10-7153553_du",
    baseYc: "7153553", baseSlug: "parova-shchitka-philips-sth7030-10-7153553",
  },
  {
    duYc: "7163805_du", duSlug: "vbud-mikvokhv-pich-whirlpool-wmd54mx-7163805_du",
    baseYc: "7163805", baseSlug: "vbud-mikvokhv-pich-whirlpool-wmd54mx-7163805",
  },
  {
    duYc: "7169040_du", duSlug: "kelykh-ecomo-vina-nabir-6x460-ml-h6142-7169040_du",
    baseYc: "7169040", baseSlug: "kelykh-ecomo-vina-nabir-6x460-ml-h6142-7169040",
  },
  {
    duYc: "7169071_du", duSlug: "sklianka-ecomo-vina-nabir-6x500-ml-vysota-10sm-c3310-7169071_du",
    baseYc: "7169071", baseSlug: "sklianka-ecomo-vina-nabir-6x500-ml-vysota-10sm-c3310-7169071",
  },
  {
    duYc: "7185654_du", duSlug: "fen-sencor-shd-9050gd-7185654_du",
    baseYc: "7185654", baseSlug: "fen-sencor-shd-9050gd-7185654",
  },
  {
    duYc: "7193446_du", duSlug: "praska-gorenje-sik2200wb-kb-936-7193446_du",
    baseYc: "7193446", baseSlug: "praska-gorenje-sik2200wb-kb-936-7193446",
  },
  {
    duYc: "7198084_du", duSlug: "pylosos-akumuliatornyi-philips-xc7163-01-7198084_du",
    baseYc: "7198084", baseSlug: "pylosos-akumuliatornyi-philips-xc7163-01-7198084",
  },
  {
    duYc: "7198085_du", duSlug: "pylosos-akumuliatornyi-philips-xc8157-01-7198085_du",
    baseYc: "7198085", baseSlug: "pylosos-akumuliatornyi-philips-xc8157-01-7198085",
  },
  {
    duYc: "7200561_du", duSlug: "aksesuary-dlia-pylososiv-sencor-svcx-0452-bags-svc-45-52-5pcs-7200561_du",
    baseYc: "7200561", baseSlug: "aksesuary-dlia-pylososiv-sencor-svcx-0452-bags-svc-45-52-5pcs-7200561",
  },
  {
    duYc: "7220881_du", duSlug: "kholodylnyk-indesit-inks-1341-w4e-7220881_du",
    baseYc: "7220881", baseSlug: "kholodylnyk-indesit-inks-1341-w4e-7220881",
  },
  {
    duYc: "7220882_du", duSlug: "vbud-kholodylnyk-beko-b3bcna294hs-7220882_du",
    baseYc: "7220882", baseSlug: "vbud-kholodylnyk-beko-b3bcna294hs-7220882",
  },
  {
    duYc: "7220896_du", duSlug: "kholodylnyk-beko-rcna406i40wn-7220896_du",
    baseYc: "7220896", baseSlug: "kholodylnyk-beko-rcna406i40wn-7220896",
  },
  {
    duYc: "7220910_du", duSlug: "morozylna-kamera-beko-rfnm200t40wn-7220910_du",
    baseYc: "7220910", baseSlug: "morozylna-kamera-beko-rfnm200t40wn-7220910",
  },
  {
    duYc: "7220911_du", duSlug: "morozylna-kamera-beko-b1rfne274w-7220911_du",
    baseYc: "7220911", baseSlug: "morozylna-kamera-beko-b1rfne274w-7220911",
  },
  {
    duYc: "7221668_du", duSlug: "sushylna-mashyna-whirlpool-wp-b9x-wbs-ua-7221668_du",
    baseYc: "7221668", baseSlug: "sushylna-mashyna-whirlpool-wp-b9x-wbs-ua-7221668",
  },
  {
    duYc: "7224534_du", duSlug: "pralno-sushylna-mashyna-lg-f2r5fg6j-7224534_du",
    baseYc: "7224534", baseSlug: "pralno-sushylna-mashyna-lg-f2r5fg6j-7224534",
  },
  {
    duYc: "7229839_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc222480aa-vc-6002-7229839_du",
    baseYc: "7229839", baseSlug: "pylosos-akumuliatornyi-gorenje-svc222480aa-vc-6002-7229839",
  },
  {
    duYc: "7232191_du", duSlug: "kholodylnyk-beko-gn163140sn-7232191_du",
    baseYc: "7232191", baseSlug: "kholodylnyk-beko-gn163140sn-7232191",
  },
  {
    duYc: "7232192_du", duSlug: "morozylna-kamera-beko-rfnm200t40sn-7232192_du",
    baseYc: "7232192", baseSlug: "morozylna-kamera-beko-rfnm200t40sn-7232192",
  },
  {
    duYc: "7240037_du", duSlug: "vodonahrivach-tesy-modeco-cloud-gcv-1504724d-c22-ecw-7240037_du",
    baseYc: "7240037", baseSlug: "vodonahrivach-tesy-modeco-cloud-gcv-1504724d-c22-ecw-7240037",
  },
  {
    duYc: "7243919_du", duSlug: "pralna-mashyna-electrolux-ews6327dxu-7243919_du",
    baseYc: "7243919", baseSlug: "pralna-mashyna-electrolux-ews6327dxu-7243919",
  },
  {
    duYc: "7246355_du", duSlug: "kholodylnyk-gorenje-nrk620eaw4-7246355_du",
    baseYc: "7246355", baseSlug: "kholodylnyk-gorenje-nrk620eaw4-7246355",
  },
  {
    duYc: "7248612_du", duSlug: "kavo-mashyna-krups-ea879ee0-7248612_du",
    baseYc: "7248612", baseSlug: "kavo-mashyna-krups-ea879ee0-7248612",
  },
  {
    duYc: "7259030_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc259400nes-v24p01fp2520eu-7259030_du",
    baseYc: "7259030", baseSlug: "pylosos-akumuliatornyi-gorenje-svc259400nes-v24p01fp2520eu-7259030",
  },
  {
    duYc: "7262655_du", duSlug: "parova-systema-tefal-gv9920e0-7262655_du",
    baseYc: "7262655", baseSlug: "parova-systema-tefal-gv9920e0-7262655",
  },
  {
    duYc: "7264937_du", duSlug: "kholodylnyk-beko-rche325k40w-7264937_du",
    baseYc: "7264937", baseSlug: "kholodylnyk-beko-rche325k40w-7264937",
  },
  {
    duYc: "7269799_du", duSlug: "vbud-dukhovka-hisense-bsa6634pbg8-bo3ps5v01-7-7269799_du",
    baseYc: "7269799", baseSlug: "vbud-dukhovka-hisense-bsa6634pbg8-bo3ps5v01-7-7269799",
  },
  {
    duYc: "7270046_du", duSlug: "kholodylnyk-lg-gr-h922hmbq-7270046_du",
    baseYc: "7270046", baseSlug: "kholodylnyk-lg-gr-h922hmbq-7270046",
  },
  {
    duYc: "7278766_du", duSlug: "praska-gorenje-sih3200bb-7278766_du",
    baseYc: "7278766", baseSlug: "praska-gorenje-sih3200bb-7278766",
  },
  {
    duYc: "7282004_du", duSlug: "kholodylnyk-hisense-rb3k330seie-bcd-330wp-7282004_du",
    baseYc: "7282004", baseSlug: "kholodylnyk-hisense-rb3k330seie-bcd-330wp-7282004",
  },
  {
    duYc: "7283135_du", duSlug: "kholodylnyk-haier-hdpr3618dnpk-7283135_du",
    baseYc: "7283135", baseSlug: "kholodylnyk-haier-hdpr3618dnpk-7283135",
  },
  {
    duYc: "7290718_du", duSlug: "mikrokhvylova-pich-gorenje-mo20ae1b5-7290718_du",
    baseYc: "7290718", baseSlug: "mikrokhvylova-pich-gorenje-mo20ae1b5-7290718",
  },
  {
    duYc: "7290720_du", duSlug: "mikrokhvylova-pich-gorenje-mo20a3b5-c20uxp75-g8e-b1a-7290720_du",
    baseYc: "7290720", baseSlug: "mikrokhvylova-pich-gorenje-mo20a3b5-c20uxp75-g8e-b1a-7290720",
  },
  {
    duYc: "7291169_du", duSlug: "kukh-inshe-gorenje-lodohenerator-giicm-7291169_du",
    baseYc: "7291169", baseSlug: "kukh-inshe-gorenje-lodohenerator-giicm-7291169",
  },
  {
    duYc: "7297145_du", duSlug: "multypich-hisense-haf3300dhcd-7297145_du",
    baseYc: "7297145", baseSlug: "multypich-hisense-haf3300dhcd-7297145",
  },
];

export const DU_PRICE_DIFF_PAIRS: readonly DuRedirectPair[] = [
  {
    duYc: "6241811_du", duSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811_du",
    baseYc: "6241811", baseSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811",
    duPrice: "7999", basePrice: "10399",
  },
  {
    duYc: "6849632_du", duSlug: "pralna-mashyna-gorenje-wnhpi-72-scsirv-ua-wflp7012-6849632_du",
    baseYc: "6849632", baseSlug: "pralna-mashyna-gorenje-wnhpi-72-scsirv-ua-wflp7012-6849632",
    duPrice: "17765", basePrice: "20999",
  },
  {
    duYc: "6873343_du", duSlug: "parova-shchitka-tefal-dt2026e1-6873343_du",
    baseYc: "6873343", baseSlug: "parova-shchitka-tefal-dt2026e1-6873343",
    duPrice: "1999", basePrice: "1839",
  },
  {
    duYc: "6988988_du", duSlug: "kelykh-luminarc-serena-line-nabir-6-550-ml-v6728-6988988_du",
    baseYc: "6988988", baseSlug: "kelykh-luminarc-serena-line-nabir-6-550-ml-v6728-6988988",
    duPrice: "1632", basePrice: "1627",
  },
  {
    duYc: "7204300_du", duSlug: "vidpariuvach-tefal-qt1811e0-7204300_du",
    baseYc: "7204300", baseSlug: "vidpariuvach-tefal-qt1811e0-7204300",
    duPrice: "13999", basePrice: "12879",
  },
  {
    duYc: "7270074_du", duSlug: "kavo-mashyna-krups-ea5088e0-7270074_du",
    baseYc: "7270074", baseSlug: "kavo-mashyna-krups-ea5088e0-7270074",
    duPrice: "15999", basePrice: "14719",
  },
];

export const DU_REDIRECT_BY_YC: ReadonlyMap<string, DuRedirectPair> = new Map(
  DU_REDIRECT_PAIRS.map((p) => [p.duYc, p])
);

export const DU_REDIRECT_SLUGS: ReadonlySet<string> = new Set(
  DU_REDIRECT_PAIRS.map((p) => p.duSlug)
);
