/**
 * GENERATED by scripts/yugcontract-du-redirect-allowlist.ts on audit 2026-09-16
 * DO NOT EDIT BY HAND — regenerate instead. Read-only audit source:
 * 293 verified _du↔base pairs (name 302/302 equal, slug derivation
 * verified 293/293 live on 2026-09-16).
 * 293 pairs -> permanent redirect to base (ALL pairs — policy
 * change 2026-09-16, owner audit fix «дві ціни на один товар»: a _du
 * shadow page with a second price must not be a live storefront/feed page;
 * the base listing is canonical). Prices of the 19 drifted pairs
 * are documented in DU_PRICE_DIFF_PAIRS for monitoring.
 * The 38 _du orphans are intentionally absent (no verified
 * base — never redirected).
 */
export interface DuRedirectPair {
  duYc: string; duSlug: string; baseYc: string; baseSlug: string;
  duPrice?: string; basePrice?: string;
}

export const DU_ALLOWLIST_AUDIT_DATE = "2026-09-16" as const;

export const DU_REDIRECT_PAIRS: readonly DuRedirectPair[] = [
  {
    duYc: "5924679_du", duSlug: "nabir-dlia-stryzhky-remington-hc-5150-5924679_du",
    baseYc: "5924679", baseSlug: "nabir-dlia-stryzhky-remington-hc-5150-5924679",
  },
  {
    duYc: "5967725_du", duSlug: "kukhonnyi-kombain-philips-hr7778-00-5967725_du",
    baseYc: "5967725", baseSlug: "kukhonnyi-kombain-philips-hr7778-00-5967725",
  },
  {
    duYc: "6051799_du", duSlug: "mikrokhvylova-pich-lg-ms2042dy-6051799_du",
    baseYc: "6051799", baseSlug: "mikrokhvylova-pich-lg-ms2042dy-6051799",
  },
  {
    duYc: "6182831_du", duSlug: "kryshka-pyrex-bombe-240-mm-b24cl00-7646-6182831_du",
    baseYc: "6182831", baseSlug: "kryshka-pyrex-bombe-240-mm-b24cl00-7646-6182831",
  },
  {
    duYc: "6213659_du", duSlug: "vbud-mikvokhv-pich-hansa-amg20bfh-6213659_du",
    baseYc: "6213659", baseSlug: "vbud-mikvokhv-pich-hansa-amg20bfh-6213659",
  },
  {
    duYc: "6235034_du", duSlug: "toster-gorenje-t-850-bk-ta8211-6235034_du",
    baseYc: "6235034", baseSlug: "toster-gorenje-t-850-bk-ta8211-6235034",
  },
  {
    duYc: "6241811_du", duSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811_du",
    baseYc: "6241811", baseSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811",
  },
  {
    duYc: "6284421_du", duSlug: "aksesuar-dlia-brytv-philips-sh50-50-6284421_du",
    baseYc: "6284421", baseSlug: "aksesuar-dlia-brytv-philips-sh50-50-6284421",
  },
  {
    duYc: "6313699_du", duSlug: "kavovarka-krapelna-gorenje-atcm-730-t-6313699_du",
    baseYc: "6313699", baseSlug: "kavovarka-krapelna-gorenje-atcm-730-t-6313699",
  },
  {
    duYc: "6344418_du", duSlug: "kukh-inshe-gorenje-r-506-e-skyborizka-6344418_du",
    baseYc: "6344418", baseSlug: "kukh-inshe-gorenje-r-506-e-skyborizka-6344418",
  },
  {
    duYc: "6345792_du", duSlug: "elektrychna-brytva-remington-pr1330-6345792_du",
    baseYc: "6345792", baseSlug: "elektrychna-brytva-remington-pr1330-6345792",
  },
  {
    duYc: "6349848_du", duSlug: "vbud-poverkhnia-beko-hiaw-64225-sx-6349848_du",
    baseYc: "6349848", baseSlug: "vbud-poverkhnia-beko-hiaw-64225-sx-6349848",
  },
  {
    duYc: "6361482_du", duSlug: "skovoroda-ringel-koriander-patelnia-hlyboka-26-sm-z-kryshkoiu-rg-1107-26-6361482_du",
    baseYc: "6361482", baseSlug: "skovoroda-ringel-koriander-patelnia-hlyboka-26-sm-z-kryshkoiu-rg-1107-26-6361482",
  },
  {
    duYc: "6361484_du", duSlug: "skovoroda-ringel-koriander-patelnia-hlyboka-28-sm-z-kryshkoiu-rg-1107-28-6361484_du",
    baseYc: "6361484", baseSlug: "skovoroda-ringel-koriander-patelnia-hlyboka-28-sm-z-kryshkoiu-rg-1107-28-6361484",
  },
  {
    duYc: "6376339_du", duSlug: "pylosos-myiuchyi-thomas-aqua-pet-family-6376339_du",
    baseYc: "6376339", baseSlug: "pylosos-myiuchyi-thomas-aqua-pet-family-6376339",
  },
  {
    duYc: "6377543_du", duSlug: "pylosos-tsyklonnyi-philips-fc9334-09-6377543_du",
    baseYc: "6377543", baseSlug: "pylosos-tsyklonnyi-philips-fc9334-09-6377543",
  },
  {
    duYc: "6381053_du", duSlug: "aksesuary-dlia-kukhonnykh-prystroiv-gorenje-vb-22-300-6381053_du",
    baseYc: "6381053", baseSlug: "aksesuary-dlia-kukhonnykh-prystroiv-gorenje-vb-22-300-6381053",
  },
  {
    duYc: "6384918_du", duSlug: "toster-gorenje-t-850-we-ta8211-6384918_du",
    baseYc: "6384918", baseSlug: "toster-gorenje-t-850-we-ta8211-6384918",
  },
  {
    duYc: "6384924_du", duSlug: "aksesuary-dlia-pylososiv-gorenje-bag-set-gb2tbr-6384924_du",
    baseYc: "6384924", baseSlug: "aksesuary-dlia-pylososiv-gorenje-bag-set-gb2tbr-6384924",
  },
  {
    duYc: "6392779_du", duSlug: "chainyk-gorenje-k-17-bk-ke01301z-gs-6392779_du",
    baseYc: "6392779", baseSlug: "chainyk-gorenje-k-17-bk-ke01301z-gs-6392779",
  },
  {
    duYc: "6398700_du", duSlug: "mikrokhvylova-pich-lg-mh6336gib-6398700_du",
    baseYc: "6398700", baseSlug: "mikrokhvylova-pich-lg-mh6336gib-6398700",
  },
  {
    duYc: "6401183_du", duSlug: "elektrosushka-gorenje-fdk-500-gcw-6401183_du",
    baseYc: "6401183", baseSlug: "elektrosushka-gorenje-fdk-500-gcw-6401183",
  },
  {
    duYc: "6415623_du", duSlug: "kavomolka-gorenje-smk-150-e-cg9139-gs-6415623_du",
    baseYc: "6415623", baseSlug: "kavomolka-gorenje-smk-150-e-cg9139-gs-6415623",
  },
  {
    duYc: "6429589_du", duSlug: "skyborizka-sencor-sfs-4050-ss-6429589_du",
    baseYc: "6429589", baseSlug: "skyborizka-sencor-sfs-4050-ss-6429589",
  },
  {
    duYc: "6441644_du", duSlug: "stolovi-prylady-ringel-calypso-nabir-stolovykh-lozhok-12-sht-rg-3113-12-2-6441644_du",
    baseYc: "6441644", baseSlug: "stolovi-prylady-ringel-calypso-nabir-stolovykh-lozhok-12-sht-rg-3113-12-2-6441644",
  },
  {
    duYc: "6443106_du", duSlug: "serviz-luminarc-diwali-light-turquoise-19-pr-p2947-6443106_du",
    baseYc: "6443106", baseSlug: "serviz-luminarc-diwali-light-turquoise-19-pr-p2947-6443106",
  },
  {
    duYc: "6446612_du", duSlug: "blender-statsionarnyi-tefal-bl438831-6446612_du",
    baseYc: "6446612", baseSlug: "blender-statsionarnyi-tefal-bl438831-6446612",
  },
  {
    duYc: "6463156_du", duSlug: "mikrokhvylova-pich-lg-ms2042db-6463156_du",
    baseYc: "6463156", baseSlug: "mikrokhvylova-pich-lg-ms2042db-6463156",
  },
  {
    duYc: "6470201_du", duSlug: "sklianka-luminarc-rhodes-nabir-6x280-ml-vysok-n9065-6470201_du",
    baseYc: "6470201", baseSlug: "sklianka-luminarc-rhodes-nabir-6x280-ml-vysok-n9065-6470201",
  },
  {
    duYc: "6471574_du", duSlug: "husiatnytsa-ringel-zitrone-roster-34x24x13-5-sm-6-3l-z-kryshkoiu-rg-2108-34-6471574_du",
    baseYc: "6471574", baseSlug: "husiatnytsa-ringel-zitrone-roster-34x24x13-5-sm-6-3l-z-kryshkoiu-rg-2108-34-6471574",
  },
  {
    duYc: "6471576_du", duSlug: "kastrulia-ringel-zitrone-black-24x16-2-sm-5-8l-z-kryshkoiu-rg-2108-24-2-bl-6471576_du",
    baseYc: "6471576", baseSlug: "kastrulia-ringel-zitrone-black-24x16-2-sm-5-8l-z-kryshkoiu-rg-2108-24-2-bl-6471576",
  },
  {
    duYc: "6474753_du", duSlug: "fen-remington-d5715-6474753_du",
    baseYc: "6474753", baseSlug: "fen-remington-d5715-6474753",
  },
  {
    duYc: "6482008_du", duSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008_du",
    baseYc: "6482008", baseSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008",
  },
  {
    duYc: "6489771_du", duSlug: "kukhonnyi-kombain-gorenje-mmc-1000-rl-6489771_du",
    baseYc: "6489771", baseSlug: "kukhonnyi-kombain-gorenje-mmc-1000-rl-6489771",
  },
  {
    duYc: "6496818_du", duSlug: "vbud-poverkhnia-beko-hilw64325sb-6496818_du",
    baseYc: "6496818", baseSlug: "vbud-poverkhnia-beko-hilw64325sb-6496818",
  },
  {
    duYc: "6524369_du", duSlug: "serviz-luminarc-diwali-light-turquoise-white-18-pr-p5912-6524369_du",
    baseYc: "6524369", baseSlug: "serviz-luminarc-diwali-light-turquoise-white-18-pr-p5912-6524369",
  },
  {
    duYc: "6527185_du", duSlug: "praska-tefal-fv5718e0-6527185_du",
    baseYc: "6527185", baseSlug: "praska-tefal-fv5718e0-6527185",
  },
  {
    duYc: "6527338_du", duSlug: "nabir-dlia-stryzhky-sencor-shp-320sl-6527338_du",
    baseYc: "6527338", baseSlug: "nabir-dlia-stryzhky-sencor-shp-320sl-6527338",
  },
  {
    duYc: "6566194_du", duSlug: "mikrokhvylova-pich-ergo-em-2040-6566194_du",
    baseYc: "6566194", baseSlug: "mikrokhvylova-pich-ergo-em-2040-6566194",
  },
  {
    duYc: "6602293_du", duSlug: "pralna-mashyna-indesit-omtwse-61051-wk-ua-6602293_du",
    baseYc: "6602293", baseSlug: "pralna-mashyna-indesit-omtwse-61051-wk-ua-6602293",
  },
  {
    duYc: "6602876_du", duSlug: "praska-gorenje-sih2800tqc-hl-8001-6602876_du",
    baseYc: "6602876", baseSlug: "praska-gorenje-sih2800tqc-hl-8001-6602876",
  },
  {
    duYc: "6603534_du", duSlug: "frytiurnytsia-sencor-sfr-8200ss-6603534_du",
    baseYc: "6603534", baseSlug: "frytiurnytsia-sencor-sfr-8200ss-6603534",
  },
  {
    duYc: "6615810_du", duSlug: "chainyk-philips-hd9318-00-6615810_du",
    baseYc: "6615810", baseSlug: "chainyk-philips-hd9318-00-6615810",
  },
  {
    duYc: "6619639_du", duSlug: "plytka-ergo-hl-2208-6619639_du",
    baseYc: "6619639", baseSlug: "plytka-ergo-hl-2208-6619639",
  },
  {
    duYc: "6624414_du", duSlug: "trymer-rowenta-tn6000f5-6624414_du",
    baseYc: "6624414", baseSlug: "trymer-rowenta-tn6000f5-6624414",
  },
  {
    duYc: "6629656_du", duSlug: "pylosos-tsyklonnyi-philips-fc9745-09-6629656_du",
    baseYc: "6629656", baseSlug: "pylosos-tsyklonnyi-philips-fc9745-09-6629656",
  },
  {
    duYc: "6629657_du", duSlug: "pylosos-tsyklonnyi-philips-xb2125-09-6629657_du",
    baseYc: "6629657", baseSlug: "pylosos-tsyklonnyi-philips-xb2125-09-6629657",
  },
  {
    duYc: "6643049_du", duSlug: "chainyk-gorenje-k-15-dww-kess4103-gs-6643049_du",
    baseYc: "6643049", baseSlug: "chainyk-gorenje-k-15-dww-kess4103-gs-6643049",
  },
  {
    duYc: "6650648_du", duSlug: "blender-pohruzhnyi-gorenje-hbc-807-qb-lw-3523g1-6650648_du",
    baseYc: "6650648", baseSlug: "blender-pohruzhnyi-gorenje-hbc-807-qb-lw-3523g1-6650648",
  },
  {
    duYc: "6651531_du", duSlug: "vypriamliach-dlia-volossia-remington-s7307-aqualisse-extreme-6651531_du",
    baseYc: "6651531", baseSlug: "vypriamliach-dlia-volossia-remington-s7307-aqualisse-extreme-6651531",
  },
  {
    duYc: "6655515_du", duSlug: "multyvarky-tefal-rk905a34-6655515_du",
    baseYc: "6655515", baseSlug: "multyvarky-tefal-rk905a34-6655515",
  },
  {
    duYc: "6656859_du", duSlug: "mikser-bez-chashi-gorenje-m460cbk-6656859_du",
    baseYc: "6656859", baseSlug: "mikser-bez-chashi-gorenje-m460cbk-6656859",
  },
  {
    duYc: "6661880_du", duSlug: "kavovarka-krapelna-russell-hobbs-27010-56-rh-bilyi-6661880_du",
    baseYc: "6661880", baseSlug: "kavovarka-krapelna-russell-hobbs-27010-56-rh-bilyi-6661880",
  },
  {
    duYc: "6662814_du", duSlug: "blender-pohruzhnyi-gorenje-hbc-802-qw-6662814_du",
    baseYc: "6662814", baseSlug: "blender-pohruzhnyi-gorenje-hbc-802-qw-6662814",
  },
  {
    duYc: "6664404_du", duSlug: "blender-pohruzhnyi-gorenje-hbc561qw-6664404_du",
    baseYc: "6664404", baseSlug: "blender-pohruzhnyi-gorenje-hbc561qw-6664404",
  },
  {
    duYc: "6665597_du", duSlug: "fen-philips-bhd300-00-6665597_du",
    baseYc: "6665597", baseSlug: "fen-philips-bhd300-00-6665597",
  },
  {
    duYc: "6666150_du", duSlug: "vbud-posudomyika-gorenje-gv-561-d10-wqp8-gdfi1-6666150_du",
    baseYc: "6666150", baseSlug: "vbud-posudomyika-gorenje-gv-561-d10-wqp8-gdfi1-6666150",
  },
  {
    duYc: "6666894_du", duSlug: "aksesuar-dlia-brytv-philips-ss12-50-6666894_du",
    baseYc: "6666894", baseSlug: "aksesuar-dlia-brytv-philips-ss12-50-6666894",
  },
  {
    duYc: "6669622_du", duSlug: "vbud-poverkhnia-gorenje-gktw642syb-bg6bb-g2b-6669622_du",
    baseYc: "6669622", baseSlug: "vbud-poverkhnia-gorenje-gktw642syb-bg6bb-g2b-6669622",
  },
  {
    duYc: "6671596_du", duSlug: "blender-pohruzhnyi-gorenje-hbc564qw-6671596_du",
    baseYc: "6671596", baseSlug: "blender-pohruzhnyi-gorenje-hbc564qw-6671596",
  },
  {
    duYc: "6672500_du", duSlug: "kavovarka-krapelna-ergo-sd-6700-6672500_du",
    baseYc: "6672500", baseSlug: "kavovarka-krapelna-ergo-sd-6700-6672500",
  },
  {
    duYc: "6711226_du", duSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226_du",
    baseYc: "6711226", baseSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226",
  },
  {
    duYc: "6719369_du", duSlug: "kholodylnyk-hisense-rb645n4bie-bcd-469wy-6719369_du",
    baseYc: "6719369", baseSlug: "kholodylnyk-hisense-rb645n4bie-bcd-469wy-6719369",
  },
  {
    duYc: "6720857_du", duSlug: "skovoroda-bravo-chef-safran-24-sm-b-kryshky-bc-1114-24-6720857_du",
    baseYc: "6720857", baseSlug: "skovoroda-bravo-chef-safran-24-sm-b-kryshky-bc-1114-24-6720857",
  },
  {
    duYc: "6721935_du", duSlug: "plyta-kombinovana-hansa-fcmx69235-6721935_du",
    baseYc: "6721935", baseSlug: "plyta-kombinovana-hansa-fcmx69235-6721935",
  },
  {
    duYc: "6745446_du", duSlug: "mikser-z-chashoiu-tefal-ht464138-6745446_du",
    baseYc: "6745446", baseSlug: "mikser-z-chashoiu-tefal-ht464138-6745446",
  },
  {
    duYc: "6746602_du", duSlug: "blendernyi-nabir-sencor-shb-4379bk-6746602_du",
    baseYc: "6746602", baseSlug: "blendernyi-nabir-sencor-shb-4379bk-6746602",
  },
  {
    duYc: "6767659_du", duSlug: "trymer-rowenta-tn3651f0-6767659_du",
    baseYc: "6767659", baseSlug: "trymer-rowenta-tn3651f0-6767659",
  },
  {
    duYc: "6790006_du", duSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006_du",
    baseYc: "6790006", baseSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006",
  },
  {
    duYc: "6790308_du", duSlug: "vbud-poverkhnia-gorenje-gtw-641-kb-bl025-6790308_du",
    baseYc: "6790308", baseSlug: "vbud-poverkhnia-gorenje-gtw-641-kb-bl025-6790308",
  },
  {
    duYc: "6805728_du", duSlug: "posudomyika-45sm-gorenje-gs541d10x-6805728_du",
    baseYc: "6805728", baseSlug: "posudomyika-45sm-gorenje-gs541d10x-6805728",
  },
  {
    duYc: "6806474_du", duSlug: "konvektor-ergo-hc-221524-6806474_du",
    baseYc: "6806474", baseSlug: "konvektor-ergo-hc-221524-6806474",
  },
  {
    duYc: "6806475_du", duSlug: "konvektor-ergo-hc-222024-6806475_du",
    baseYc: "6806475", baseSlug: "konvektor-ergo-hc-222024-6806475",
  },
  {
    duYc: "6807009_du", duSlug: "hryl-gorenje-sm-703-gcg-sw-008-6807009_du",
    baseYc: "6807009", baseSlug: "hryl-gorenje-sm-703-gcg-sw-008-6807009",
  },
  {
    duYc: "6807693_du", duSlug: "posudomyika-45sm-gorenje-gs520e15s-wqp8-7606v-6807693_du",
    baseYc: "6807693", baseSlug: "posudomyika-45sm-gorenje-gs520e15s-wqp8-7606v-6807693",
  },
  {
    duYc: "6809216_du", duSlug: "chainyk-amica-kf-1013-6809216_du",
    baseYc: "6809216", baseSlug: "chainyk-amica-kf-1013-6809216",
  },
  {
    duYc: "6810251_du", duSlug: "kholodylnyk-gorenje-nrk620eabg4-6810251_du",
    baseYc: "6810251", baseSlug: "kholodylnyk-gorenje-nrk620eabg4-6810251",
  },
  {
    duYc: "6811303_du", duSlug: "skovoroda-oscar-best-offer-26-sm-b-kryshky-osr-1108-26-1-6811303_du",
    baseYc: "6811303", baseSlug: "skovoroda-oscar-best-offer-26-sm-b-kryshky-osr-1108-26-1-6811303",
  },
  {
    duYc: "6811444_du", duSlug: "vbud-posudomyika-gorenje-gv520e15-wqp8-7712r-6811444_du",
    baseYc: "6811444", baseSlug: "vbud-posudomyika-gorenje-gv520e15-wqp8-7712r-6811444",
  },
  {
    duYc: "6814742_du", duSlug: "fen-rowenta-cv581lf0-6814742_du",
    baseYc: "6814742", baseSlug: "fen-rowenta-cv581lf0-6814742",
  },
  {
    duYc: "6819086_du", duSlug: "vbud-dukhovka-gorenje-bsa-6747-a04bgwi-bo3sa5i01-7-6819086_du",
    baseYc: "6819086", baseSlug: "vbud-dukhovka-gorenje-bsa-6747-a04bgwi-bo3sa5i01-7-6819086",
  },
  {
    duYc: "6821456_du", duSlug: "kukh-prylad-tramontina-ability-lopatka-z-prorizamy-neilon-chorna-25155-100-6821456_du",
    baseYc: "6821456", baseSlug: "kukh-prylad-tramontina-ability-lopatka-z-prorizamy-neilon-chorna-25155-100-6821456",
  },
  {
    duYc: "6823611_du", duSlug: "mikrokhvylova-pich-samsung-ms23k3614aw-ua-6823611_du",
    baseYc: "6823611", baseSlug: "mikrokhvylova-pich-samsung-ms23k3614aw-ua-6823611",
  },
  {
    duYc: "6840744_du", duSlug: "serviz-luminarc-louis-xv-white-18-pr-v2940-6840744_du",
    baseYc: "6840744", baseSlug: "serviz-luminarc-louis-xv-white-18-pr-v2940-6840744",
  },
  {
    duYc: "6849632_du", duSlug: "pralna-mashyna-gorenje-wnhpi-72-scsirv-ua-wflp7012-6849632_du",
    baseYc: "6849632", baseSlug: "pralna-mashyna-gorenje-wnhpi-72-scsirv-ua-wflp7012-6849632",
  },
  {
    duYc: "6860389_du", duSlug: "mikrokhvylova-pich-gorenje-mo17e1bh-6860389_du",
    baseYc: "6860389", baseSlug: "mikrokhvylova-pich-gorenje-mo17e1bh-6860389",
  },
  {
    duYc: "6865314_du", duSlug: "kivsh-ringel-zira-z-kryshkoiu-20-sm-2-2l-rg-41006-20-6865314_du",
    baseYc: "6865314", baseSlug: "kivsh-ringel-zira-z-kryshkoiu-20-sm-2-2l-rg-41006-20-6865314",
  },
  {
    duYc: "6865317_du", duSlug: "kastrulia-ringel-zira-z-kryshkoiu-vysoka-24-sm-6-3l-rg-21006-24h-6865317_du",
    baseYc: "6865317", baseSlug: "kastrulia-ringel-zira-z-kryshkoiu-vysoka-24-sm-6-3l-rg-21006-24h-6865317",
  },
  {
    duYc: "6870556_du", duSlug: "vbud-dukhovka-beko-bbie13100xc-6870556_du",
    baseYc: "6870556", baseSlug: "vbud-dukhovka-beko-bbie13100xc-6870556",
  },
  {
    duYc: "6871226_du", duSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syw-mxy55z-6871226_du",
    baseYc: "6871226", baseSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syw-mxy55z-6871226",
  },
  {
    duYc: "6871229_du", duSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syb-mxy55z-6871229_du",
    baseYc: "6871229", baseSlug: "vbud-mikvokhv-pich-gorenje-bm235g1syb-mxy55z-6871229",
  },
  {
    duYc: "6873343_du", duSlug: "parova-shchitka-tefal-dt2026e1-6873343_du",
    baseYc: "6873343", baseSlug: "parova-shchitka-tefal-dt2026e1-6873343",
  },
  {
    duYc: "6875715_du", duSlug: "vbud-dukhovka-gorenje-bps-6747-a06bg-6875715_du",
    baseYc: "6875715", baseSlug: "vbud-dukhovka-gorenje-bps-6747-a06bg-6875715",
  },
  {
    duYc: "6877219_du", duSlug: "vbud-dukhovka-gorenje-bos-67371-syb-bo3co8s01-1-6877219_du",
    baseYc: "6877219", baseSlug: "vbud-dukhovka-gorenje-bos-67371-syb-bo3co8s01-1-6877219",
  },
  {
    duYc: "6882306_du", duSlug: "morozylna-kamera-gorenje-fn-619-eew5-6882306_du",
    baseYc: "6882306", baseSlug: "morozylna-kamera-gorenje-fn-619-eew5-6882306",
  },
  {
    duYc: "6884549_du", duSlug: "fen-remington-ac5860-e51-botanicals-hairdryer-6884549_du",
    baseYc: "6884549", baseSlug: "fen-remington-ac5860-e51-botanicals-hairdryer-6884549",
  },
  {
    duYc: "6885495_du", duSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495_du",
    baseYc: "6885495", baseSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495",
  },
  {
    duYc: "6885815_du", duSlug: "sokodavka-gorenje-cj30e-jc3400-gs-6885815_du",
    baseYc: "6885815", baseSlug: "sokodavka-gorenje-cj30e-jc3400-gs-6885815",
  },
  {
    duYc: "6887045_du", duSlug: "kelykh-luminarc-raindrop-nabir-6kh250-ml-h5701-6887045_du",
    baseYc: "6887045", baseSlug: "kelykh-luminarc-raindrop-nabir-6kh250-ml-h5701-6887045",
  },
  {
    duYc: "6887050_du", duSlug: "kelykh-luminarc-raindrop-nabir-6kh450-ml-q5488-6887050_du",
    baseYc: "6887050", baseSlug: "kelykh-luminarc-raindrop-nabir-6kh450-ml-q5488-6887050",
  },
  {
    duYc: "6895802_du", duSlug: "kholodylnyk-hisense-rt641n4afe1-bcd-456wy-6895802_du",
    baseYc: "6895802", baseSlug: "kholodylnyk-hisense-rt641n4afe1-bcd-456wy-6895802",
  },
  {
    duYc: "6895806_du", duSlug: "kholodylnyk-hisense-rt641n4wfe1-bcd-456wyr-6895806_du",
    baseYc: "6895806", baseSlug: "kholodylnyk-hisense-rt641n4wfe1-bcd-456wyr-6895806",
  },
  {
    duYc: "6895807_du", duSlug: "kholodylnyk-hisense-rt641n4wie1-bcd-456wyr-6895807_du",
    baseYc: "6895807", baseSlug: "kholodylnyk-hisense-rt641n4wie1-bcd-456wyr-6895807",
  },
  {
    duYc: "6906793_du", duSlug: "kholodylnyk-hisense-rb395n4bwe-bcd-300wy-6906793_du",
    baseYc: "6906793", baseSlug: "kholodylnyk-hisense-rb395n4bwe-bcd-300wy-6906793",
  },
  {
    duYc: "6909546_du", duSlug: "vakuumator-gorenje-vs120es-vs2660-6909546_du",
    baseYc: "6909546", baseSlug: "vakuumator-gorenje-vs120es-vs2660-6909546",
  },
  {
    duYc: "6910447_du", duSlug: "hryl-gorenje-gcg2100s-gc5006-gs-6910447_du",
    baseYc: "6910447", baseSlug: "hryl-gorenje-gcg2100s-gc5006-gs-6910447",
  },
  {
    duYc: "6911589_du", duSlug: "kukhonnyi-kombain-gorenje-s450xe-podribniuvach-6911589_du",
    baseYc: "6911589", baseSlug: "kukhonnyi-kombain-gorenje-s450xe-podribniuvach-6911589",
  },
  {
    duYc: "6914082_du", duSlug: "vahy-kukhonni-sencor-sks-7100ss-6914082_du",
    baseYc: "6914082", baseSlug: "vahy-kukhonni-sencor-sks-7100ss-6914082",
  },
  {
    duYc: "6915580_du", duSlug: "mikrokhvylova-pich-hisense-h20mobp1-m20xyz-6915580_du",
    baseYc: "6915580", baseSlug: "mikrokhvylova-pich-hisense-h20mobp1-m20xyz-6915580",
  },
  {
    duYc: "6915675_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc-144-fbk-vc2930c-gs-6915675_du",
    baseYc: "6915675", baseSlug: "pylosos-akumuliatornyi-gorenje-svc-144-fbk-vc2930c-gs-6915675",
  },
  {
    duYc: "6922846_du", duSlug: "pralna-mashyna-gorenje-wnhpi-62scsirv-ua-wflp6012-plast-bak-6922846_du",
    baseYc: "6922846", baseSlug: "pralna-mashyna-gorenje-wnhpi-62scsirv-ua-wflp6012-plast-bak-6922846",
  },
  {
    duYc: "6924604_du", duSlug: "kholodylnyk-hisense-rb440n4afe-bcd-331w-6924604_du",
    baseYc: "6924604", baseSlug: "kholodylnyk-hisense-rb440n4afe-bcd-331w-6924604",
  },
  {
    duYc: "6932802_du", duSlug: "kondytsioner-ergo-aci-0923-swn-w-6932802_du",
    baseYc: "6932802", baseSlug: "kondytsioner-ergo-aci-0923-swn-w-6932802",
  },
  {
    duYc: "6932803_du", duSlug: "kondytsioner-ergo-aci-1223-swn-w-6932803_du",
    baseYc: "6932803", baseSlug: "kondytsioner-ergo-aci-1223-swn-w-6932803",
  },
  {
    duYc: "6932805_du", duSlug: "kondytsioner-ergo-ac-0703-swn-6932805_du",
    baseYc: "6932805", baseSlug: "kondytsioner-ergo-ac-0703-swn-6932805",
  },
  {
    duYc: "6932807_du", duSlug: "kondytsioner-ergo-ac-1203-swn-6932807_du",
    baseYc: "6932807", baseSlug: "kondytsioner-ergo-ac-1203-swn-6932807",
  },
  {
    duYc: "6940144_du", duSlug: "kavovarka-kapsulna-krups-genio-s-plus-kp340510-6940144_du",
    baseYc: "6940144", baseSlug: "kavovarka-kapsulna-krups-genio-s-plus-kp340510-6940144",
  },
  {
    duYc: "6943335_du", duSlug: "mikrokhvylova-pich-hisense-h23mobs5hg-6943335_du",
    baseYc: "6943335", baseSlug: "mikrokhvylova-pich-hisense-h23mobs5hg-6943335",
  },
  {
    duYc: "6944367_du", duSlug: "morozylna-kamera-gorenje-fhc42eaw-6944367_du",
    baseYc: "6944367", baseSlug: "morozylna-kamera-gorenje-fhc42eaw-6944367",
  },
  {
    duYc: "6944463_du", duSlug: "morozylna-kamera-gorenje-fh-30-eaw-6944463_du",
    baseYc: "6944463", baseSlug: "morozylna-kamera-gorenje-fh-30-eaw-6944463",
  },
  {
    duYc: "6949363_du", duSlug: "vbud-dukhovka-gorenje-bpsa-6747-dgwi-6949363_du",
    baseYc: "6949363", baseSlug: "vbud-dukhovka-gorenje-bpsa-6747-dgwi-6949363",
  },
  {
    duYc: "6965695_du", duSlug: "kholodylnyk-hisense-rq7p522stfe-6965695_du",
    baseYc: "6965695", baseSlug: "kholodylnyk-hisense-rq7p522stfe-6965695",
  },
  {
    duYc: "6965981_du", duSlug: "blender-statsionarnyi-tefal-perfect-mix-bl87g831-6965981_du",
    baseYc: "6965981", baseSlug: "blender-statsionarnyi-tefal-perfect-mix-bl87g831-6965981",
  },
  {
    duYc: "6966588_du", duSlug: "parova-shchitka-tefal-dt1034e1-6966588_du",
    baseYc: "6966588", baseSlug: "parova-shchitka-tefal-dt1034e1-6966588",
  },
  {
    duYc: "6971347_du", duSlug: "vodonahrivach-tiki-comfort-h-80v9-gbh-80-6971347_du",
    baseYc: "6971347", baseSlug: "vodonahrivach-tiki-comfort-h-80v9-gbh-80-6971347",
  },
  {
    duYc: "6976884_du", duSlug: "toster-moulinex-lt2m0810-6976884_du",
    baseYc: "6976884", baseSlug: "toster-moulinex-lt2m0810-6976884",
  },
  {
    duYc: "6977230_du", duSlug: "kholodylnyk-gorenje-r492pw-6977230_du",
    baseYc: "6977230", baseSlug: "kholodylnyk-gorenje-r492pw-6977230",
  },
  {
    duYc: "6980268_du", duSlug: "kholodylnyk-hisense-rb435n4bce-6980268_du",
    baseYc: "6980268", baseSlug: "kholodylnyk-hisense-rb435n4bce-6980268",
  },
  {
    duYc: "6980326_du", duSlug: "pylosos-akumuliatornyi-dreame-wet-dry-vacuum-cleaner-h11-core-6980326_du",
    baseYc: "6980326", baseSlug: "pylosos-akumuliatornyi-dreame-wet-dry-vacuum-cleaner-h11-core-6980326",
  },
  {
    duYc: "6984810_du", duSlug: "praska-gorenje-sich2200rbc-hc-3001rw-6984810_du",
    baseYc: "6984810", baseSlug: "praska-gorenje-sich2200rbc-hc-3001rw-6984810",
  },
  {
    duYc: "6984812_du", duSlug: "blender-statsionarnyi-gorenje-bsm-600-e-bl1403-gs-6984812_du",
    baseYc: "6984812", baseSlug: "blender-statsionarnyi-gorenje-bsm-600-e-bl1403-gs-6984812",
  },
  {
    duYc: "6984815_du", duSlug: "morozylna-kamera-gorenje-f39epw4-6984815_du",
    baseYc: "6984815", baseSlug: "morozylna-kamera-gorenje-f39epw4-6984815",
  },
  {
    duYc: "6984818_du", duSlug: "kholodylnyk-gorenje-nrk6182ps4-6984818_du",
    baseYc: "6984818", baseSlug: "kholodylnyk-gorenje-nrk6182ps4-6984818",
  },
  {
    duYc: "6984892_du", duSlug: "morozylna-kamera-hisense-fv298n4ace-6984892_du",
    baseYc: "6984892", baseSlug: "morozylna-kamera-hisense-fv298n4ace-6984892",
  },
  {
    duYc: "6985215_du", duSlug: "multypich-tefal-ey801815-6985215_du",
    baseYc: "6985215", baseSlug: "multypich-tefal-ey801815-6985215",
  },
  {
    duYc: "6985231_du", duSlug: "buterbrodnytsia-tefal-sw383d10-6985231_du",
    baseYc: "6985231", baseSlug: "buterbrodnytsia-tefal-sw383d10-6985231",
  },
  {
    duYc: "6985785_du", duSlug: "vbud-poverkhnia-gorenje-gi6401bsce-mc-if7017b1-a-6985785_du",
    baseYc: "6985785", baseSlug: "vbud-poverkhnia-gorenje-gi6401bsce-mc-if7017b1-a-6985785",
  },
  {
    duYc: "6987709_du", duSlug: "kholodylnyk-gorenje-nrk418ecs4-6987709_du",
    baseYc: "6987709", baseSlug: "kholodylnyk-gorenje-nrk418ecs4-6987709",
  },
  {
    duYc: "6988685_du", duSlug: "chainyk-amica-kf-4012-6988685_du",
    baseYc: "6988685", baseSlug: "chainyk-amica-kf-4012-6988685",
  },
  {
    duYc: "6988689_du", duSlug: "chainyk-amica-kf-1002-6988689_du",
    baseYc: "6988689", baseSlug: "chainyk-amica-kf-1002-6988689",
  },
  {
    duYc: "6988918_du", duSlug: "multypich-philips-na120-00-6988918_du",
    baseYc: "6988918", baseSlug: "multypich-philips-na120-00-6988918",
  },
  {
    duYc: "6988988_du", duSlug: "kelykh-luminarc-serena-line-nabir-6-550-ml-v6728-6988988_du",
    baseYc: "6988988", baseSlug: "kelykh-luminarc-serena-line-nabir-6-550-ml-v6728-6988988",
  },
  {
    duYc: "6990159_du", duSlug: "kholodylnyk-hisense-rq758n4sbse-6990159_du",
    baseYc: "6990159", baseSlug: "kholodylnyk-hisense-rq758n4sbse-6990159",
  },
  {
    duYc: "6990162_du", duSlug: "kholodylnyk-hisense-rq760n4ife-6990162_du",
    baseYc: "6990162", baseSlug: "kholodylnyk-hisense-rq760n4ife-6990162",
  },
  {
    duYc: "6990585_du", duSlug: "morozylna-kamera-gorenje-fh50eaw-6990585_du",
    baseYc: "6990585", baseSlug: "morozylna-kamera-gorenje-fh50eaw-6990585",
  },
  {
    duYc: "6993614_du", duSlug: "morozhenytsia-gorenje-icm10w-ice-1031-6993614_du",
    baseYc: "6993614", baseSlug: "morozhenytsia-gorenje-icm10w-ice-1031-6993614",
  },
  {
    duYc: "6993837_du", duSlug: "mikrokhvylova-pich-hisense-h30mobs10hc-6993837_du",
    baseYc: "6993837", baseSlug: "mikrokhvylova-pich-hisense-h30mobs10hc-6993837",
  },
  {
    duYc: "6996159_du", duSlug: "pralna-mashyna-haier-hw90-b14939s8-6996159_du",
    baseYc: "6996159", baseSlug: "pralna-mashyna-haier-hw90-b14939s8-6996159",
  },
  {
    duYc: "6996304_du", duSlug: "kastrulia-iq-be-active-aliuminiieva-18-sm-1-7-l-z-kryshkoiu-iq-2048-18-6996304_du",
    baseYc: "6996304", baseSlug: "kastrulia-iq-be-active-aliuminiieva-18-sm-1-7-l-z-kryshkoiu-iq-2048-18-6996304",
  },
  {
    duYc: "6996307_du", duSlug: "soteinyk-iq-be-active-z-dvoma-ruchkamy-aliuminiievyi-28-sm-4-0-l-z-kryshkoiu-iq-6996307_du",
    baseYc: "6996307", baseSlug: "soteinyk-iq-be-active-z-dvoma-ruchkamy-aliuminiievyi-28-sm-4-0-l-z-kryshkoiu-iq-6996307",
  },
  {
    duYc: "6998665_du", duSlug: "morozylna-kamera-gorenje-fh43eaw-6998665_du",
    baseYc: "6998665", baseSlug: "morozylna-kamera-gorenje-fh43eaw-6998665",
  },
  {
    duYc: "6998788_du", duSlug: "mikser-bez-chashi-gorenje-m-500-dc-6998788_du",
    baseYc: "6998788", baseSlug: "mikser-bez-chashi-gorenje-m-500-dc-6998788",
  },
  {
    duYc: "7002722_du", duSlug: "pliashka-shtof-viva-stof-d-mitsnykh-napoiv-500-ml-v-up-wb500-7002722_du",
    baseYc: "7002722", baseSlug: "pliashka-shtof-viva-stof-d-mitsnykh-napoiv-500-ml-v-up-wb500-7002722",
  },
  {
    duYc: "7005374_du", duSlug: "mikrokhvylova-pich-samsung-ms20a3010ah-ol-7005374_du",
    baseYc: "7005374", baseSlug: "mikrokhvylova-pich-samsung-ms20a3010ah-ol-7005374",
  },
  {
    duYc: "7006966_du", duSlug: "pylosos-tsyklonnyi-gorenje-vce01sfabkr-7006966_du",
    baseYc: "7006966", baseSlug: "pylosos-tsyklonnyi-gorenje-vce01sfabkr-7006966",
  },
  {
    duYc: "7007001_du", duSlug: "sushylna-mashyna-hisense-dh7s107bw-7007001_du",
    baseYc: "7007001", baseSlug: "sushylna-mashyna-hisense-dh7s107bw-7007001",
  },
  {
    duYc: "7019427_du", duSlug: "praska-gorenje-sih3200wr-hl-8002-7019427_du",
    baseYc: "7019427", baseSlug: "praska-gorenje-sih3200wr-hl-8002-7019427",
  },
  {
    duYc: "7022284_du", duSlug: "trymer-philips-oneblade-pro-360-qp6542-15-dlia-oblychchia-ta-tila-7022284_du",
    baseYc: "7022284", baseSlug: "trymer-philips-oneblade-pro-360-qp6542-15-dlia-oblychchia-ta-tila-7022284",
  },
  {
    duYc: "7023706_du", duSlug: "elektropich-hisense-hom45d-7023706_du",
    baseYc: "7023706", baseSlug: "elektropich-hisense-hom45d-7023706",
  },
  {
    duYc: "7024506_du", duSlug: "kukhonna-mashyna-gorenje-mmc1000scb-7024506_du",
    baseYc: "7024506", baseSlug: "kukhonna-mashyna-gorenje-mmc1000scb-7024506",
  },
  {
    duYc: "7024832_du", duSlug: "hryl-philips-hd6307-70-7024832_du",
    baseYc: "7024832", baseSlug: "hryl-philips-hd6307-70-7024832",
  },
  {
    duYc: "7025027_du", duSlug: "fen-philips-bhd538-30-7025027_du",
    baseYc: "7025027", baseSlug: "fen-philips-bhd538-30-7025027",
  },
  {
    duYc: "7035514_du", duSlug: "fen-shchitka-rowenta-ub9540f0-7035514_du",
    baseYc: "7035514", baseSlug: "fen-shchitka-rowenta-ub9540f0-7035514",
  },
  {
    duYc: "7035560_du", duSlug: "vypriamliach-dlia-volossia-rowenta-sf8120f0-7035560_du",
    baseYc: "7035560", baseSlug: "vypriamliach-dlia-volossia-rowenta-sf8120f0-7035560",
  },
  {
    duYc: "7035567_du", duSlug: "mikrokhvylova-pich-hisense-h20mobp1hi-7035567_du",
    baseYc: "7035567", baseSlug: "mikrokhvylova-pich-hisense-h20mobp1hi-7035567",
  },
  {
    duYc: "7040730_du", duSlug: "toster-gorenje-t800db-7040730_du",
    baseYc: "7040730", baseSlug: "toster-gorenje-t800db-7040730",
  },
  {
    duYc: "7043027_du", duSlug: "mikrokhvylova-pich-gorenje-mo20e1t4-7043027_du",
    baseYc: "7043027", baseSlug: "mikrokhvylova-pich-gorenje-mo20e1t4-7043027",
  },
  {
    duYc: "7048618_du", duSlug: "parova-shchitka-tefal-jf4032e0-7048618_du",
    baseYc: "7048618", baseSlug: "parova-shchitka-tefal-jf4032e0-7048618",
  },
  {
    duYc: "7051690_du", duSlug: "skorovarka-hisense-hmc6sbk-7051690_du",
    baseYc: "7051690", baseSlug: "skorovarka-hisense-hmc6sbk-7051690",
  },
  {
    duYc: "7051727_du", duSlug: "miasorubka-gorenje-mg2001sb-7051727_du",
    baseYc: "7051727", baseSlug: "miasorubka-gorenje-mg2001sb-7051727",
  },
  {
    duYc: "7053687_du", duSlug: "fen-shchitka-rowenta-cf9840f0-7053687_du",
    baseYc: "7053687", baseSlug: "fen-shchitka-rowenta-cf9840f0-7053687",
  },
  {
    duYc: "7053878_du", duSlug: "mikrokhvylova-pich-hisense-h23mobs4hi-7053878_du",
    baseYc: "7053878", baseSlug: "mikrokhvylova-pich-hisense-h23mobs4hi-7053878",
  },
  {
    duYc: "7056170_du", duSlug: "mikrokhvylova-pich-hisense-h23mobs5h4-7056170_du",
    baseYc: "7056170", baseSlug: "mikrokhvylova-pich-hisense-h23mobs5h4-7056170",
  },
  {
    duYc: "7056171_du", duSlug: "mikrokhvylova-pich-hisense-h25mobs4hgi-7056171_du",
    baseYc: "7056171", baseSlug: "mikrokhvylova-pich-hisense-h25mobs4hgi-7056171",
  },
  {
    duYc: "7058051_du", duSlug: "plyta-sklokeramika-electrolux-lkr664166x-7058051_du",
    baseYc: "7058051", baseSlug: "plyta-sklokeramika-electrolux-lkr664166x-7058051",
  },
  {
    duYc: "7061694_du", duSlug: "kondytsioner-ergo-aci-0935-swn-w-7061694_du",
    baseYc: "7061694", baseSlug: "kondytsioner-ergo-aci-0935-swn-w-7061694",
  },
  {
    duYc: "7061695_du", duSlug: "kondytsioner-ergo-aci-1235-swn-w-7061695_du",
    baseYc: "7061695", baseSlug: "kondytsioner-ergo-aci-1235-swn-w-7061695",
  },
  {
    duYc: "7064284_du", duSlug: "multypich-philips-na332-00-7064284_du",
    baseYc: "7064284", baseSlug: "multypich-philips-na332-00-7064284",
  },
  {
    duYc: "7067155_du", duSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155_du",
    baseYc: "7067155", baseSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155",
  },
  {
    duYc: "7068492_du", duSlug: "chainyk-gorenje-k17dpw-7068492_du",
    baseYc: "7068492", baseSlug: "chainyk-gorenje-k17dpw-7068492",
  },
  {
    duYc: "7069182_du", duSlug: "vbud-dukhovka-gorenje-bop6737e02bk-7069182_du",
    baseYc: "7069182", baseSlug: "vbud-dukhovka-gorenje-bop6737e02bk-7069182",
  },
  {
    duYc: "7069371_du", duSlug: "pylosos-myiuchyi-dreame-h14-dual-hhv25a-7069371_du",
    baseYc: "7069371", baseSlug: "pylosos-myiuchyi-dreame-h14-dual-hhv25a-7069371",
  },
  {
    duYc: "7076766_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc288191fsiigo-7076766_du",
    baseYc: "7076766", baseSlug: "pylosos-akumuliatornyi-gorenje-svc288191fsiigo-7076766",
  },
  {
    duYc: "7083113_du", duSlug: "parova-shchitka-tefal-dt9814f0-7083113_du",
    baseYc: "7083113", baseSlug: "parova-shchitka-tefal-dt9814f0-7083113",
  },
  {
    duYc: "7086538_du", duSlug: "kholodylnyk-hisense-rq5p470sale-7086538_du",
    baseYc: "7086538", baseSlug: "kholodylnyk-hisense-rq5p470sale-7086538",
  },
  {
    duYc: "7087286_du", duSlug: "vodonahrivach-tiki-gbf-80-ua-7087286_du",
    baseYc: "7087286", baseSlug: "vodonahrivach-tiki-gbf-80-ua-7087286",
  },
  {
    duYc: "7088391_du", duSlug: "kukhonna-mashyna-gorenje-mmc1500scx-7088391_du",
    baseYc: "7088391", baseSlug: "kukhonna-mashyna-gorenje-mmc1500scx-7088391",
  },
  {
    duYc: "7088394_du", duSlug: "buterbrodnytsia-gorenje-wm1400sb-7088394_du",
    baseYc: "7088394", baseSlug: "buterbrodnytsia-gorenje-wm1400sb-7088394",
  },
  {
    duYc: "7092284_du", duSlug: "kastrulia-bravo-chef-20-sm-3-6-l-z-kryshkoiu-nerzh-bc-2001-20p-7092284_du",
    baseYc: "7092284", baseSlug: "kastrulia-bravo-chef-20-sm-3-6-l-z-kryshkoiu-nerzh-bc-2001-20p-7092284",
  },
  {
    duYc: "7094152_du", duSlug: "hryl-gorenje-sm701sb-7094152_du",
    baseYc: "7094152", baseSlug: "hryl-gorenje-sm701sb-7094152",
  },
  {
    duYc: "7109149_du", duSlug: "chainyk-ergo-gl-8010-7109149_du",
    baseYc: "7109149", baseSlug: "chainyk-ergo-gl-8010-7109149",
  },
  {
    duYc: "7109372_du", duSlug: "hryl-gorenje-gcg2000sd-7109372_du",
    baseYc: "7109372", baseSlug: "hryl-gorenje-gcg2000sd-7109372",
  },
  {
    duYc: "7110070_du", duSlug: "kholodylnyk-lg-gc-b459fnpw-7110070_du",
    baseYc: "7110070", baseSlug: "kholodylnyk-lg-gc-b459fnpw-7110070",
  },
  {
    duYc: "7110073_du", duSlug: "kholodylnyk-lg-gc-b509fnpw-7110073_du",
    baseYc: "7110073", baseSlug: "kholodylnyk-lg-gc-b509fnpw-7110073",
  },
  {
    duYc: "7110886_du", duSlug: "blendernyi-nabir-ergo-ehb-8000-7110886_du",
    baseYc: "7110886", baseSlug: "blendernyi-nabir-ergo-ehb-8000-7110886",
  },
  {
    duYc: "7110888_du", duSlug: "blendernyi-nabir-ergo-ehb-9500-7110888_du",
    baseYc: "7110888", baseSlug: "blendernyi-nabir-ergo-ehb-9500-7110888",
  },
  {
    duYc: "7111320_du", duSlug: "multypich-philips-na231-00-7111320_du",
    baseYc: "7111320", baseSlug: "multypich-philips-na231-00-7111320",
  },
  {
    duYc: "7112060_du", duSlug: "chainyk-gorenje-elektrochainyk-k-17-ds-743903-7112060_du",
    baseYc: "7112060", baseSlug: "chainyk-gorenje-elektrochainyk-k-17-ds-743903-7112060",
  },
  {
    duYc: "7119324_du", duSlug: "infrachervonyi-ergo-hi-2520-7119324_du",
    baseYc: "7119324", baseSlug: "infrachervonyi-ergo-hi-2520-7119324",
  },
  {
    duYc: "7119325_du", duSlug: "infrachervonyi-ergo-hi-2525-7119325_du",
    baseYc: "7119325", baseSlug: "infrachervonyi-ergo-hi-2525-7119325",
  },
  {
    duYc: "7119327_du", duSlug: "aksesuary-dlia-obihrivachiv-ergo-stiika-dlia-obihrivacha-1800-ss-7119327_du",
    baseYc: "7119327", baseSlug: "aksesuary-dlia-obihrivachiv-ergo-stiika-dlia-obihrivacha-1800-ss-7119327",
  },
  {
    duYc: "7120212_du", duSlug: "chainyk-amica-kf-1022-7120212_du",
    baseYc: "7120212", baseSlug: "chainyk-amica-kf-1022-7120212",
  },
  {
    duYc: "7120215_du", duSlug: "hryl-amica-gk-4011-7120215_du",
    baseYc: "7120215", baseSlug: "hryl-amica-gk-4011-7120215",
  },
  {
    duYc: "7126071_du", duSlug: "multypich-philips-na555-00-7126071_du",
    baseYc: "7126071", baseSlug: "multypich-philips-na555-00-7126071",
  },
  {
    duYc: "7133018_du", duSlug: "skovoroda-bravo-chef-hlyboka-20-sm-bc-1102-20-h-7133018_du",
    baseYc: "7133018", baseSlug: "skovoroda-bravo-chef-hlyboka-20-sm-bc-1102-20-h-7133018",
  },
  {
    duYc: "7133024_du", duSlug: "skovoroda-bravo-chef-26-sm-bc-1102-26-7133024_du",
    baseYc: "7133024", baseSlug: "skovoroda-bravo-chef-26-sm-bc-1102-26-7133024",
  },
  {
    duYc: "7138500_du", duSlug: "pylosos-myiuchyi-thomas-amfibia-pro-evo-7138500_du",
    baseYc: "7138500", baseSlug: "pylosos-myiuchyi-thomas-amfibia-pro-evo-7138500",
  },
  {
    duYc: "7153553_du", duSlug: "parova-shchitka-philips-sth7030-10-7153553_du",
    baseYc: "7153553", baseSlug: "parova-shchitka-philips-sth7030-10-7153553",
  },
  {
    duYc: "7154561_du", duSlug: "parova-shchitka-gorenje-gs2100bkv-7154561_du",
    baseYc: "7154561", baseSlug: "parova-shchitka-gorenje-gs2100bkv-7154561",
  },
  {
    duYc: "7156888_du", duSlug: "pylosos-robot-dreame-bot-d20-ultra-7156888_du",
    baseYc: "7156888", baseSlug: "pylosos-robot-dreame-bot-d20-ultra-7156888",
  },
  {
    duYc: "7156889_du", duSlug: "pylosos-robot-dreame-l40-ultra-ce-white-7156889_du",
    baseYc: "7156889", baseSlug: "pylosos-robot-dreame-l40-ultra-ce-white-7156889",
  },
  {
    duYc: "7156890_du", duSlug: "pylosos-robot-dreame-bot-l40-ultra-ce-black-7156890_du",
    baseYc: "7156890", baseSlug: "pylosos-robot-dreame-bot-l40-ultra-ce-black-7156890",
  },
  {
    duYc: "7156900_du", duSlug: "elektrosushka-gorenje-fdk400de-7156900_du",
    baseYc: "7156900", baseSlug: "elektrosushka-gorenje-fdk400de-7156900",
  },
  {
    duYc: "7159943_du", duSlug: "chainyk-gorenje-k17w-7159943_du",
    baseYc: "7159943", baseSlug: "chainyk-gorenje-k17w-7159943",
  },
  {
    duYc: "7159944_du", duSlug: "chainyk-gorenje-k17spb-7159944_du",
    baseYc: "7159944", baseSlug: "chainyk-gorenje-k17spb-7159944",
  },
  {
    duYc: "7163805_du", duSlug: "vbud-mikvokhv-pich-whirlpool-wmd54mx-7163805_du",
    baseYc: "7163805", baseSlug: "vbud-mikvokhv-pich-whirlpool-wmd54mx-7163805",
  },
  {
    duYc: "7166755_du", duSlug: "sokodavka-gorenje-jc400be-7166755_du",
    baseYc: "7166755", baseSlug: "sokodavka-gorenje-jc400be-7166755",
  },
  {
    duYc: "7169040_du", duSlug: "kelykh-ecomo-vina-nabir-6x460-ml-h6142-7169040_du",
    baseYc: "7169040", baseSlug: "kelykh-ecomo-vina-nabir-6x460-ml-h6142-7169040",
  },
  {
    duYc: "7169071_du", duSlug: "sklianka-ecomo-vina-nabir-6x500-ml-vysota-10sm-c3310-7169071_du",
    baseYc: "7169071", baseSlug: "sklianka-ecomo-vina-nabir-6x500-ml-vysota-10sm-c3310-7169071",
  },
  {
    duYc: "7173534_du", duSlug: "pralno-sushylna-mashyna-hisense-wd5i8043bwf-7173534_du",
    baseYc: "7173534", baseSlug: "pralno-sushylna-mashyna-hisense-wd5i8043bwf-7173534",
  },
  {
    duYc: "7173544_du", duSlug: "pralna-mashyna-hisense-wf5i9043bbfs-7173544_du",
    baseYc: "7173544", baseSlug: "pralna-mashyna-hisense-wf5i9043bbfs-7173544",
  },
  {
    duYc: "7185653_du", duSlug: "paroochysnyk-sencor-ssc-3510wh-7185653_du",
    baseYc: "7185653", baseSlug: "paroochysnyk-sencor-ssc-3510wh-7185653",
  },
  {
    duYc: "7185654_du", duSlug: "fen-sencor-shd-9050gd-7185654_du",
    baseYc: "7185654", baseSlug: "fen-sencor-shd-9050gd-7185654",
  },
  {
    duYc: "7185819_du", duSlug: "pralna-mashyna-electrolux-ews6427bu-7185819_du",
    baseYc: "7185819", baseSlug: "pralna-mashyna-electrolux-ews6427bu-7185819",
  },
  {
    duYc: "7193446_du", duSlug: "praska-gorenje-sik2200wb-kb-936-7193446_du",
    baseYc: "7193446", baseSlug: "praska-gorenje-sik2200wb-kb-936-7193446",
  },
  {
    duYc: "7194071_du", duSlug: "pralna-mashyna-samsung-ww90fg3m05twlf-7194071_du",
    baseYc: "7194071", baseSlug: "pralna-mashyna-samsung-ww90fg3m05twlf-7194071",
  },
  {
    duYc: "7196133_du", duSlug: "pylosos-myiuchyi-dreame-g10-pro-7196133_du",
    baseYc: "7196133", baseSlug: "pylosos-myiuchyi-dreame-g10-pro-7196133",
  },
  {
    duYc: "7196146_du", duSlug: "pylosos-tsyklonnyi-gorenje-vce01g2aw-cj173-7196146_du",
    baseYc: "7196146", baseSlug: "pylosos-tsyklonnyi-gorenje-vce01g2aw-cj173-7196146",
  },
  {
    duYc: "7198084_du", duSlug: "pylosos-akumuliatornyi-philips-xc7163-01-7198084_du",
    baseYc: "7198084", baseSlug: "pylosos-akumuliatornyi-philips-xc7163-01-7198084",
  },
  {
    duYc: "7198085_du", duSlug: "pylosos-akumuliatornyi-philips-xc8157-01-7198085_du",
    baseYc: "7198085", baseSlug: "pylosos-akumuliatornyi-philips-xc8157-01-7198085",
  },
  {
    duYc: "7200561_du", duSlug: "aksesuary-dlia-pylososiv-sencor-svcx-0452-bags-svc-45-52-5pcs-7200561_du",
    baseYc: "7200561", baseSlug: "aksesuary-dlia-pylososiv-sencor-svcx-0452-bags-svc-45-52-5pcs-7200561",
  },
  {
    duYc: "7204300_du", duSlug: "vidpariuvach-tefal-qt1811e0-7204300_du",
    baseYc: "7204300", baseSlug: "vidpariuvach-tefal-qt1811e0-7204300",
  },
  {
    duYc: "7204416_du", duSlug: "praska-ergo-des-2090-7204416_du",
    baseYc: "7204416", baseSlug: "praska-ergo-des-2090-7204416",
  },
  {
    duYc: "7220881_du", duSlug: "kholodylnyk-indesit-inks-1341-w4e-7220881_du",
    baseYc: "7220881", baseSlug: "kholodylnyk-indesit-inks-1341-w4e-7220881",
  },
  {
    duYc: "7220882_du", duSlug: "vbud-kholodylnyk-beko-b3bcna294hs-7220882_du",
    baseYc: "7220882", baseSlug: "vbud-kholodylnyk-beko-b3bcna294hs-7220882",
  },
  {
    duYc: "7220883_du", duSlug: "vbud-kholodylnyk-beko-b5bcna325hs-7220883_du",
    baseYc: "7220883", baseSlug: "vbud-kholodylnyk-beko-b5bcna325hs-7220883",
  },
  {
    duYc: "7220887_du", duSlug: "kholodylnyk-beko-rcsa366k40xbn-7220887_du",
    baseYc: "7220887", baseSlug: "kholodylnyk-beko-rcsa366k40xbn-7220887",
  },
  {
    duYc: "7220891_du", duSlug: "kholodylnyk-beko-rcna366k40wn-7220891_du",
    baseYc: "7220891", baseSlug: "kholodylnyk-beko-rcna366k40wn-7220891",
  },
  {
    duYc: "7220896_du", duSlug: "kholodylnyk-beko-rcna406i40wn-7220896_du",
    baseYc: "7220896", baseSlug: "kholodylnyk-beko-rcna406i40wn-7220896",
  },
  {
    duYc: "7220910_du", duSlug: "morozylna-kamera-beko-rfnm200t40wn-7220910_du",
    baseYc: "7220910", baseSlug: "morozylna-kamera-beko-rfnm200t40wn-7220910",
  },
  {
    duYc: "7220911_du", duSlug: "morozylna-kamera-beko-b1rfne274w-7220911_du",
    baseYc: "7220911", baseSlug: "morozylna-kamera-beko-b1rfne274w-7220911",
  },
  {
    duYc: "7221668_du", duSlug: "sushylna-mashyna-whirlpool-wp-b9x-wbs-ua-7221668_du",
    baseYc: "7221668", baseSlug: "sushylna-mashyna-whirlpool-wp-b9x-wbs-ua-7221668",
  },
  {
    duYc: "7221704_du", duSlug: "pralna-mashyna-indesit-btw-s50400-eu-n-7221704_du",
    baseYc: "7221704", baseSlug: "pralna-mashyna-indesit-btw-s50400-eu-n-7221704",
  },
  {
    duYc: "7222127_du", duSlug: "kholodylnyk-indesit-i55t1-612s-7222127_du",
    baseYc: "7222127", baseSlug: "kholodylnyk-indesit-i55t1-612s-7222127",
  },
  {
    duYc: "7224277_du", duSlug: "blender-pohruzhnyi-tefal-hb67mb30-7224277_du",
    baseYc: "7224277", baseSlug: "blender-pohruzhnyi-tefal-hb67mb30-7224277",
  },
  {
    duYc: "7224534_du", duSlug: "pralno-sushylna-mashyna-lg-f2r5fg6j-7224534_du",
    baseYc: "7224534", baseSlug: "pralno-sushylna-mashyna-lg-f2r5fg6j-7224534",
  },
  {
    duYc: "7229839_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc222480aa-vc-6002-7229839_du",
    baseYc: "7229839", baseSlug: "pylosos-akumuliatornyi-gorenje-svc222480aa-vc-6002-7229839",
  },
  {
    duYc: "7231791_du", duSlug: "chainyk-gorenje-k17os-7231791_du",
    baseYc: "7231791", baseSlug: "chainyk-gorenje-k17os-7231791",
  },
  {
    duYc: "7232191_du", duSlug: "kholodylnyk-beko-gn163140sn-7232191_du",
    baseYc: "7232191", baseSlug: "kholodylnyk-beko-gn163140sn-7232191",
  },
  {
    duYc: "7232192_du", duSlug: "morozylna-kamera-beko-rfnm200t40sn-7232192_du",
    baseYc: "7232192", baseSlug: "morozylna-kamera-beko-rfnm200t40sn-7232192",
  },
  {
    duYc: "7240037_du", duSlug: "vodonahrivach-tesy-modeco-cloud-gcv-1504724d-c22-ecw-7240037_du",
    baseYc: "7240037", baseSlug: "vodonahrivach-tesy-modeco-cloud-gcv-1504724d-c22-ecw-7240037",
  },
  {
    duYc: "7242869_du", duSlug: "multypich-gorenje-af1800st-7242869_du",
    baseYc: "7242869", baseSlug: "multypich-gorenje-af1800st-7242869",
  },
  {
    duYc: "7243919_du", duSlug: "pralna-mashyna-electrolux-ews6327dxu-7243919_du",
    baseYc: "7243919", baseSlug: "pralna-mashyna-electrolux-ews6327dxu-7243919",
  },
  {
    duYc: "7246355_du", duSlug: "kholodylnyk-gorenje-nrk620eaw4-7246355_du",
    baseYc: "7246355", baseSlug: "kholodylnyk-gorenje-nrk620eaw4-7246355",
  },
  {
    duYc: "7246356_du", duSlug: "vbud-kholodylnyk-gorenje-nrki519e41-7246356_du",
    baseYc: "7246356", baseSlug: "vbud-kholodylnyk-gorenje-nrki519e41-7246356",
  },
  {
    duYc: "7248612_du", duSlug: "kavo-mashyna-krups-ea879ee0-7248612_du",
    baseYc: "7248612", baseSlug: "kavo-mashyna-krups-ea879ee0-7248612",
  },
  {
    duYc: "7248819_du", duSlug: "vbud-kholodylnyk-gorenje-nrki517e41-7248819_du",
    baseYc: "7248819", baseSlug: "vbud-kholodylnyk-gorenje-nrki517e41-7248819",
  },
  {
    duYc: "7248822_du", duSlug: "kholodylnyk-gorenje-nrs917e41x-7248822_du",
    baseYc: "7248822", baseSlug: "kholodylnyk-gorenje-nrs917e41x-7248822",
  },
  {
    duYc: "7248826_du", duSlug: "kholodylnyk-gorenje-nrs917e41bxwd-7248826_du",
    baseYc: "7248826", baseSlug: "kholodylnyk-gorenje-nrs917e41bxwd-7248826",
  },
  {
    duYc: "7248827_du", duSlug: "kholodylnyk-gorenje-nrs917e41xwd-7248827_du",
    baseYc: "7248827", baseSlug: "kholodylnyk-gorenje-nrs917e41xwd-7248827",
  },
  {
    duYc: "7250275_du", duSlug: "kholodylnyk-lg-gc-b509emkm-7250275_du",
    baseYc: "7250275", baseSlug: "kholodylnyk-lg-gc-b509emkm-7250275",
  },
  {
    duYc: "7250291_du", duSlug: "sushylna-mashyna-electrolux-ew7d495udu-7250291_du",
    baseYc: "7250291", baseSlug: "sushylna-mashyna-electrolux-ew7d495udu-7250291",
  },
  {
    duYc: "7257886_du", duSlug: "vahy-napolni-tefal-bm9720f0-7257886_du",
    baseYc: "7257886", baseSlug: "vahy-napolni-tefal-bm9720f0-7257886",
  },
  {
    duYc: "7259026_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc259449ndco-v24p01fp2535eu-7259026_du",
    baseYc: "7259026", baseSlug: "pylosos-akumuliatornyi-gorenje-svc259449ndco-v24p01fp2535eu-7259026",
  },
  {
    duYc: "7259027_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc252426ffca-vc3996-gs-7259027_du",
    baseYc: "7259027", baseSlug: "pylosos-akumuliatornyi-gorenje-svc252426ffca-vc3996-gs-7259027",
  },
  {
    duYc: "7259028_du", duSlug: "pylosos-tsyklonnyi-gorenje-vce08g6aego-tpc02-7259028_du",
    baseYc: "7259028", baseSlug: "pylosos-tsyklonnyi-gorenje-vce08g6aego-tpc02-7259028",
  },
  {
    duYc: "7259030_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc259400nes-v24p01fp2520eu-7259030_du",
    baseYc: "7259030", baseSlug: "pylosos-akumuliatornyi-gorenje-svc259400nes-v24p01fp2520eu-7259030",
  },
  {
    duYc: "7259489_du", duSlug: "vodonahrivach-gorenje-dryheat-50-7259489_du",
    baseYc: "7259489", baseSlug: "vodonahrivach-gorenje-dryheat-50-7259489",
  },
  {
    duYc: "7262655_du", duSlug: "parova-systema-tefal-gv9920e0-7262655_du",
    baseYc: "7262655", baseSlug: "parova-systema-tefal-gv9920e0-7262655",
  },
  {
    duYc: "7264937_du", duSlug: "kholodylnyk-beko-rche325k40w-7264937_du",
    baseYc: "7264937", baseSlug: "kholodylnyk-beko-rche325k40w-7264937",
  },
  {
    duYc: "7266827_du", duSlug: "pralna-mashyna-lg-f2x5ps5w-7266827_du",
    baseYc: "7266827", baseSlug: "pralna-mashyna-lg-f2x5ps5w-7266827",
  },
  {
    duYc: "7267156_du", duSlug: "pylosos-akumuliatornyi-gorenje-svc259441nfgo-7267156_du",
    baseYc: "7267156", baseSlug: "pylosos-akumuliatornyi-gorenje-svc259441nfgo-7267156",
  },
  {
    duYc: "7269797_du", duSlug: "blender-pohruzhnyi-gorenje-hbx1200eb-hb-70212-7269797_du",
    baseYc: "7269797", baseSlug: "blender-pohruzhnyi-gorenje-hbx1200eb-hb-70212-7269797",
  },
  {
    duYc: "7269799_du", duSlug: "vbud-dukhovka-hisense-bsa6634pbg8-bo3ps5v01-7-7269799_du",
    baseYc: "7269799", baseSlug: "vbud-dukhovka-hisense-bsa6634pbg8-bo3ps5v01-7-7269799",
  },
  {
    duYc: "7270046_du", duSlug: "kholodylnyk-lg-gr-h922hmbq-7270046_du",
    baseYc: "7270046", baseSlug: "kholodylnyk-lg-gr-h922hmbq-7270046",
  },
  {
    duYc: "7270074_du", duSlug: "kavo-mashyna-krups-ea5088e0-7270074_du",
    baseYc: "7270074", baseSlug: "kavo-mashyna-krups-ea5088e0-7270074",
  },
  {
    duYc: "7278766_du", duSlug: "praska-gorenje-sih3200bb-7278766_du",
    baseYc: "7278766", baseSlug: "praska-gorenje-sih3200bb-7278766",
  },
  {
    duYc: "7281960_du", duSlug: "pylosos-akumuliatornyi-wet-dry-gorenje-sfc216100g-7281960_du",
    baseYc: "7281960", baseSlug: "pylosos-akumuliatornyi-wet-dry-gorenje-sfc216100g-7281960",
  },
  {
    duYc: "7282004_du", duSlug: "kholodylnyk-hisense-rb3k330seie-bcd-330wp-7282004_du",
    baseYc: "7282004", baseSlug: "kholodylnyk-hisense-rb3k330seie-bcd-330wp-7282004",
  },
  {
    duYc: "7283115_du", duSlug: "vbud-dukhovka-gorenje-bo6737e02bg-7283115_du",
    baseYc: "7283115", baseSlug: "vbud-dukhovka-gorenje-bo6737e02bg-7283115",
  },
  {
    duYc: "7283135_du", duSlug: "kholodylnyk-haier-hdpr3618dnpk-7283135_du",
    baseYc: "7283135", baseSlug: "kholodylnyk-haier-hdpr3618dnpk-7283135",
  },
  {
    duYc: "7283431_du", duSlug: "pralna-mashyna-haier-hw70-b14929-7283431_du",
    baseYc: "7283431", baseSlug: "pralna-mashyna-haier-hw70-b14929-7283431",
  },
  {
    duYc: "7290695_du", duSlug: "mikrokhvylova-pich-gorenje-mo20ce1w5-7290695_du",
    baseYc: "7290695", baseSlug: "mikrokhvylova-pich-gorenje-mo20ce1w5-7290695",
  },
  {
    duYc: "7290706_du", duSlug: "mikrokhvylova-pich-gorenje-mo20e1b5-c20mxp99-g7e-b1b-7290706_du",
    baseYc: "7290706", baseSlug: "mikrokhvylova-pich-gorenje-mo20e1b5-c20mxp99-g7e-b1b-7290706",
  },
  {
    duYc: "7290718_du", duSlug: "mikrokhvylova-pich-gorenje-mo20ae1b5-7290718_du",
    baseYc: "7290718", baseSlug: "mikrokhvylova-pich-gorenje-mo20ae1b5-7290718",
  },
  {
    duYc: "7290720_du", duSlug: "mikrokhvylova-pich-gorenje-mo20a3b5-c20uxp75-g8e-b1a-7290720_du",
    baseYc: "7290720", baseSlug: "mikrokhvylova-pich-gorenje-mo20a3b5-c20uxp75-g8e-b1a-7290720",
  },
  {
    duYc: "7291169_du", duSlug: "kukh-inshe-gorenje-lodohenerator-giicm-7291169_du",
    baseYc: "7291169", baseSlug: "kukh-inshe-gorenje-lodohenerator-giicm-7291169",
  },
  {
    duYc: "7294289_du", duSlug: "pylosos-robot-dreame-l40-ultra-a-white-7294289_du",
    baseYc: "7294289", baseSlug: "pylosos-robot-dreame-l40-ultra-a-white-7294289",
  },
  {
    duYc: "7295172_du", duSlug: "kavo-mashyna-krups-ea918ge0-7295172_du",
    baseYc: "7295172", baseSlug: "kavo-mashyna-krups-ea918ge0-7295172",
  },
  {
    duYc: "7297145_du", duSlug: "multypich-hisense-haf3300dhcd-7297145_du",
    baseYc: "7297145", baseSlug: "multypich-hisense-haf3300dhcd-7297145",
  },
  {
    duYc: "7297148_du", duSlug: "morozylna-kamera-gorenje-fh20e6w5-zs20782-7297148_du",
    baseYc: "7297148", baseSlug: "morozylna-kamera-gorenje-fh20e6w5-zs20782-7297148",
  },
  {
    duYc: "7298177_du", duSlug: "kukh-inshe-russell-hobbs-28780-56-povilnovarka-bronte-soft-navy-7l-7298177_du",
    baseYc: "7298177", baseSlug: "kukh-inshe-russell-hobbs-28780-56-povilnovarka-bronte-soft-navy-7l-7298177",
  },
  {
    duYc: "7306143_du", duSlug: "multypich-gorenje-haf2700dha-af-d1105ah-7306143_du",
    baseYc: "7306143", baseSlug: "multypich-gorenje-haf2700dha-af-d1105ah-7306143",
  },
];

export const DU_PRICE_DIFF_PAIRS: readonly DuRedirectPair[] = [
  {
    duYc: "6241811_du", duSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811_du",
    baseYc: "6241811", baseSlug: "vbud-poverkhnia-whirlpool-akt-8210-lx-6241811",
    duPrice: "7999", basePrice: "10399",
  },
  {
    duYc: "6482008_du", duSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008_du",
    baseYc: "6482008", baseSlug: "plyta-sklokeramika-beko-fsm57300gx-6482008",
    duPrice: "20099", basePrice: "20799",
  },
  {
    duYc: "6615810_du", duSlug: "chainyk-philips-hd9318-00-6615810_du",
    baseYc: "6615810", baseSlug: "chainyk-philips-hd9318-00-6615810",
    duPrice: "1199", basePrice: "1499",
  },
  {
    duYc: "6711226_du", duSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226_du",
    baseYc: "6711226", baseSlug: "kholodylnyk-hisense-rb440n4gbe-bcd-331w-6711226",
    duPrice: "27999", basePrice: "29499",
  },
  {
    duYc: "6790006_du", duSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006_du",
    baseYc: "6790006", baseSlug: "vbud-dukhovka-gorenje-bsa-6737-e15bg-bo3sa7c01-1-6790006",
    duPrice: "22999", basePrice: "24699",
  },
  {
    duYc: "6873343_du", duSlug: "parova-shchitka-tefal-dt2026e1-6873343_du",
    baseYc: "6873343", baseSlug: "parova-shchitka-tefal-dt2026e1-6873343",
    duPrice: "1999", basePrice: "1839",
  },
  {
    duYc: "6885495_du", duSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495_du",
    baseYc: "6885495", baseSlug: "mikrokhvylova-pich-gorenje-mo-20-e1wh-6885495",
    duPrice: "3399", basePrice: "3499",
  },
  {
    duYc: "6895807_du", duSlug: "kholodylnyk-hisense-rt641n4wie1-bcd-456wyr-6895807_du",
    baseYc: "6895807", baseSlug: "kholodylnyk-hisense-rt641n4wie1-bcd-456wyr-6895807",
    duPrice: "44599", basePrice: "39999",
  },
  {
    duYc: "6965695_du", duSlug: "kholodylnyk-hisense-rq7p522stfe-6965695_du",
    baseYc: "6965695", baseSlug: "kholodylnyk-hisense-rq7p522stfe-6965695",
    duPrice: "90999", basePrice: "84999",
  },
  {
    duYc: "6990159_du", duSlug: "kholodylnyk-hisense-rq758n4sbse-6990159_du",
    baseYc: "6990159", baseSlug: "kholodylnyk-hisense-rq758n4sbse-6990159",
    duPrice: "62099", basePrice: "57999",
  },
  {
    duYc: "7067155_du", duSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155_du",
    baseYc: "7067155", baseSlug: "hlechyk-ringel-grey-line-g-1800-ml-rg-0003-1800-g-7067155",
    duPrice: "566", basePrice: "392",
  },
  {
    duYc: "7083113_du", duSlug: "parova-shchitka-tefal-dt9814f0-7083113_du",
    baseYc: "7083113", baseSlug: "parova-shchitka-tefal-dt9814f0-7083113",
    duPrice: "4999", basePrice: "5999",
  },
  {
    duYc: "7109372_du", duSlug: "hryl-gorenje-gcg2000sd-7109372_du",
    baseYc: "7109372", baseSlug: "hryl-gorenje-gcg2000sd-7109372",
    duPrice: "3689", basePrice: "3869",
  },
  {
    duYc: "7111320_du", duSlug: "multypich-philips-na231-00-7111320_du",
    baseYc: "7111320", baseSlug: "multypich-philips-na231-00-7111320",
    duPrice: "5899", basePrice: "4999",
  },
  {
    duYc: "7194071_du", duSlug: "pralna-mashyna-samsung-ww90fg3m05twlf-7194071_du",
    baseYc: "7194071", baseSlug: "pralna-mashyna-samsung-ww90fg3m05twlf-7194071",
    duPrice: "17999", basePrice: "19499",
  },
  {
    duYc: "7204300_du", duSlug: "vidpariuvach-tefal-qt1811e0-7204300_du",
    baseYc: "7204300", baseSlug: "vidpariuvach-tefal-qt1811e0-7204300",
    duPrice: "13999", basePrice: "12879",
  },
  {
    duYc: "7232191_du", duSlug: "kholodylnyk-beko-gn163140sn-7232191_du",
    baseYc: "7232191", baseSlug: "kholodylnyk-beko-gn163140sn-7232191",
    duPrice: "41599", basePrice: "42999",
  },
  {
    duYc: "7248827_du", duSlug: "kholodylnyk-gorenje-nrs917e41xwd-7248827_du",
    baseYc: "7248827", baseSlug: "kholodylnyk-gorenje-nrs917e41xwd-7248827",
    duPrice: "39999", basePrice: "35999",
  },
  {
    duYc: "7270074_du", duSlug: "kavo-mashyna-krups-ea5088e0-7270074_du",
    baseYc: "7270074", baseSlug: "kavo-mashyna-krups-ea5088e0-7270074",
    duPrice: "15999", basePrice: "14719",
  },
];

export const DU_REDIRECT_BY_YC: ReadonlyMap<string, DuRedirectPair> = new Map(
  DU_REDIRECT_PAIRS.map((p) => [p.duYc, p])
);

export const DU_REDIRECT_SLUGS: ReadonlySet<string> = new Set(
  DU_REDIRECT_PAIRS.map((p) => p.duSlug)
);
